### ISSUE TITLE
Summary of successes and failures of model testing

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#101]
Models marked with a 🎉 have passed all tests I could come up with!

All the models are now tested in a script called (Testing_Model_et_al_year.pynb with an associated xlsx with the same name) in the "calibration" then "testing" folder

**1. Moore et al. 1998.**  🎉 :
--
Successful tests:
1) Compare Psat from Vesical to calibration dataset gradient of Psat Vesical vs. calibration dataset pressure (v good considering scatter, particularly within calibration range)
2) Compare H2O calculated in spreadsheet and VESIcal (<0.5 % discrepency)

**2. Dixon (VolatileCalc)**
--
Positives - Saturation pressures as similar to VolatileCalc as VolatileCalc is to the Dixon Macro. Calculated fluids match
Negatives - Still something not quite right with isobars. see #116 
 

**3. Liu et al., 2005** 🎉
--
Positives - Experimental pressures match VESIcal saturation pressures for Water, and synthetic arrays for Water and Carbon match pressure figures in paper. Matches isobar diagram

**4. Iacono-Marziano et al., 2012** 🎉
--
Positives - Saturation pressures match the web app extremely well now. So do calculated volatiles. 
Negatives - Their isobar diagram is wrong, not sure if should call them out on it. see #117 

**5. Shishkina et al., 2014** 🎉
--
Positives - Experimental pressures match VESIcal well for Carbon and water

**6. Magmasat**** :
--
Recreates saturation pressures from Bennett et al. (2019) from app. Isobars match plots in paper except for MORB see #117 

**7. Allison et al., 2019**
--
Allison Carbon now working, strange behavoir when mixing with water models. See #110  
_PW: Things left to test - Isobars vs. spreadsheet. Check Psat for other compositions_

**Comment by simonwmatthews** [comment]
Thanks for the summary!

The values in in Table 6 (for use with Eqn 13) differ between the manuscript and the webapp:
Manuscript:
a = 0.53, b = 2.35, B = -3.37, C = -0.02

Webapp:		
a = 0.52096846, b = 2.11575907, B = -3.24443335, C = -0.02238884

**Comment by simonwmatthews** [comment]
Dixon discrepancies are (virtually) no more! The remaining discrepancies were down to the EOS being used.

**Comment by kaylai** [comment]
This is great, Penny, thanks for putting this all in one place! Will get working on these.

**Comment by simonwmatthews** [comment]
And I can do even better than virtually no discrepancies now! If we get rid of the pre-processing step, the results match perfectly. This can be done by adding "preprocess_samples=False" to the call to the calculate method. Perhaps its worth just ditching the automatic pre-processing and rely on people having normalised their data appropriately already?

**Comment by PennyWieser** [comment]
I think maybe ditch automatic preprocessing and add it as an option? @kaylai what does magmasat do?  I've found it really weird sometimes if you change the normalisation in some of the methods, it doesn't do anything as its been normalized earlier. I think best make it as transparent as possible what the code is doing (e.g., nothing by default), and if people really want to play around they can. I guess it only really matters for more H2O-rich stuff, and particularly these synthetic arrays I've been generating where majors are constant but H2O is changing.

**Comment by kaylai** [comment]
I agree it’s not transparent enough. I think making preprocessing optional is a must, and perhaps making the default “don’t preprocess” is best. In some cases not, however. For example I think the MooreWater model will break if things aren’t normalized. Simon feel free to make this change if you like as I won’t be able to get to this until Monday, and I can deal with MagmaSat (don’t think any preprocessing is necessary) and MooreWater.

**Comment by kaylai** [comment]
Simon, it looks like you implemented the change to make preprocess_samples=False by default except for MixedFluid models. This looks good to me. Are there still any issues to do with preprocessing, or is that issue resolved?

**Comment by kaylai** [comment]
Update: MooreWater performing better now. Issue #98 closed!

**Comment by simonwmatthews** [comment]
Update: Liu isobars are now going the right way! Issue #84 closed!

**Comment by kaylai** [comment]
Update: I have implemented a method to calculate smoothed isobars and isopleths. Issue #97 closed!

**Comment by PennyWieser** [comment]
Closing this now - as almost all models working and have tidied up all model scripts. Only issues left are with Dixon (1997), which have separate issues open still.
