### ISSUE TITLE
Inconsistent output column headings

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#102]
Hi @kaylai and @simonwmatthews , didn't want to change this incase there was a reason for this, but the output dataframe headings are different for some functions for magmasat and the other models. This means if you have say, a plot of "calculate dissolved volatiles" and you switch models, you have to change your plotting script, which while not the end of the world is a bit irritating. 

E.g., Using Dixon, Shishkina, etc
![image](https://user-images.githubusercontent.com/65668673/87137944-95f50580-c295-11ea-9f63-2b9585b24a5d.png)
While using Magmasat:
![image](https://user-images.githubusercontent.com/65668673/87137993-a60ce500-c295-11ea-854a-5f9b80a8502f.png)

Given that the isobars, isopleths scripts returns H2O_liq  and CO2_liq for all models, I think it would best if calc_dissolved_volatiles did too?

**Comment by simonwmatthews** [comment]
This is because MagmaSat has a verbose option, whilst the other VESIcal methods don't. The column headings themselves should be consistent though (when they are output)? 

The verbose option could be implemented.

Related question for @kaylai- how does MagmaSat calculate FluidProportion_wt in this example? I must be missing something, but I would have thought the fluid proportion can take any value as long as X_fluid and its partial pressure remains the same? Or is this just the value used to find a solution?

**Comment by PennyWieser** [comment]
Simon I'm not sure what you mean by column headings? 

E.g., if I have a plotting script: 
`fig, ax1 = plt.subplots(figsize = (17/2,20/2))
plt.scatter(dissolved_syn_noH2O['H2O'], (10**4)*dissolved_syn_noH2O['CO2'],  s=100, edgecolors='gray', facecolors='silver', marker='o', zorder=5)`
If I change my model from say Shishkina to Magmasat, I then have to adjust it
fig, ax1 = plt.subplots(figsize = (17/2,20/2))
plt.scatter(dissolved_syn_noH2O['H2O_liq'], (10**4)*dissolved_syn_noH2O['CO2_liq'],  s=100, edgecolors='gray', facecolors='silver', marker='o', zorder=5)

**Comment by simonwmatthews** [comment]
Ah, sorry. The column headings for the DataFrames/Spreadsheets should be the same? Sorry, that's what I was thinking of with column headings. 

With 'CO2' vs 'CO2_liq' in the dictionaries, I can change that. I'll do that later today.

**Comment by PennyWieser** [comment]
Sorry, my bad, still not down with the python lingo.

**Comment by simonwmatthews** [comment]
No, my fault for getting confused! The dict return from MixedFluid.calculate_dissolved_volatiles() should now be {'H2O_liq':...,'CO2_liq':...}.
