### ISSUE TITLE
calc_dissolved_volatiles for mixed fluid models?

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#103]
I am probably missing something very obvious, but why does VESIcal return a batch calculate dissolved volatiles forShishkinaCarbon, ShishkinaWater, etc. etc. (e.g., all single models), magmasat, but not Dixon, Shishkina, IaconoMarziano. I'm trying to compare calc_dissolved_volatiles with the online app for IaconoMarziano.

E.g.,
` myfile_Inverse.calculate_dissolved_volatiles(temperature="Temp", pressure="Press", X_fluid="XH2Oin", print_status=True, model='ShishkinaWater')`
 returns an output
` myfile_Inverse.calculate_dissolved_volatiles(temperature="Temp", pressure="Press", X_fluid="XH2Oin", print_status=True)`
returns an output
but
`myfile_Inverse.calculate_dissolved_volatiles(temperature="Temp", pressure="Press", X_fluid="XH2Oin", print_status=True, model='Shishkina')`
just puts "Calculation Failed" and fils H2O_liq_Vesical with Nans as for CO2_liq_Vesical

Is it just that the iteration hasn't been written for the mixed models? If so, I guess its probably worth saying that in the text (I spent ages trying to get an output haha)

Individual samples work with these mixed fluid models.

**Comment by simonwmatthews** [comment]
Unintended consequence of changing dictionary keys. Should be fixed now.
