### ISSUE TITLE
calculate_dissolved_volatiles cares about H2O and CO2 headings?

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#104]
VESIcal and IaconoMarziano's web app for calculate_dissolved_volatiles don't match that well. I think this is due to normalisation happening in VESical?

The output from calculate_dissolved_volatiles varies depending on whether the spreadsheet being loaded in has any numbers in the H2O and CO2 headings. 
E.g., If no H2O and CO2 values
![image](https://user-images.githubusercontent.com/65668673/87294608-e7063300-c4fb-11ea-9655-cbaa30eaf4db.png)
You get this output
![image](https://user-images.githubusercontent.com/65668673/87294632-ee2d4100-c4fb-11ea-871f-72ea7d2e03ff.png)

But if you do fill up those values (in this case, I had filled them with the outputs of the VESIcal so as to test whether calc_diss volatiles and calc saturation pressure are internally consistent)
you get different answers. 
![image](https://user-images.githubusercontent.com/65668673/87294731-0f8e2d00-c4fc-11ea-8ea1-b3f02f9a8edb.png)
![image](https://user-images.githubusercontent.com/65668673/87294732-1157f080-c4fc-11ea-8262-2ac1628cf4cd.png)

I'm assuming this is due to normalization? as you are basically reducing the wt% of the other oxides by doing this? or is calculate_dissolved_volatiles actually looking in the H2O-CO2 column as a first guess? I can see people encountering this problem if they have measured H2O and CO2 contents, so those columns are full, but want to play around with the calc_dissolved_volatiles function

**Comment by simonwmatthews** [comment]
Almost certainly renormalization. calculate_dissolved_volatiles() doesn't use the H2O and CO2 columns directly, but they would have an indirect effect on the normalization. 

You should be able to test this by adding "preprocess_sample = False" to the call to calculate_dissolved_volatiles(...). 

However, I'm going to set no pre-processing as the default option when I work on the code this afternoon.

**Comment by PennyWieser** [comment]
This is sort of what I meant by the fact sometimes putting these calls in doesn't do anything:
![image](https://user-images.githubusercontent.com/65668673/87296212-541ac800-c4fe-11ea-917a-5399109bdd0f.png)
![image](https://user-images.githubusercontent.com/65668673/87296328-7dd3ef00-c4fe-11ea-90b2-b8e5bfc13404.png)

**Comment by simonwmatthews** [comment]
Ah, yep, just checked what the code is doing. The variable doesn't propagate in the batch calculations, just needs **kwargs adding in the right places. Will fix this later today. Thanks for spotting it!

**Comment by simonwmatthews** [comment]
@PennyWieser This should be fixed now, when you get a chance could you try running the same check again please?

**Comment by PennyWieser** [comment]
Fixed!
