### ISSUE TITLE
Weird Allison mixing behavoir

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#105]
Firstly, @simonwmatthews, great job on fixing AllisonCarbon - now recreates the spreadsheet almost exactly. Means its really easy now to plot up the responses to show how important it is to use these models for Alkali basalts so it was definetly worth the effort getting the Carbon model working!
![image](https://user-images.githubusercontent.com/65668673/87315193-1462d900-c51c-11ea-983a-dca937da3af3.png)

The mixed models I've been creating in the following way are behaving a bit weirdly:
`mixed_model_Moore_sunset = v.MixedFluid({'CO2':v.AllisonCarbon(model_fit='thermodynamic', model_loc='sunset'),
                            'H2O':v.MooreWater()})
mixed_model_Moore_Dixon = v.MixedFluid({'CO2':v.DixonCarbon(),
                            'H2O':v.MooreWater()})
mixed_model_Dixon_sunset = v.MixedFluid({'CO2':v.AllisonCarbon(model_fit='thermodynamic', model_loc='sunset'),
                            'H2O':v.DixonWater()})
mixed_model_Shish_sunset = v.MixedFluid({'CO2':v.AllisonCarbon(model_fit='thermodynamic', model_loc='sunset'),
                            'H2O':v.ShishkinaWater()})
mixed_model_IM_sunset = v.MixedFluid({'CO2':v.AllisonCarbon(model_fit='thermodynamic', model_loc='sunset'),
                            'H2O':v.IaconoMarzianoWater()})`

For the sunset crater composition, I have taken a constant CO2 content (500 ppm) and variable H2O contents and used Allisons spreadsheet to calculate the PSat, and then compared it to VESIcal:
![image](https://user-images.githubusercontent.com/65668673/87315370-59870b00-c51c-11ea-8b0d-81694d10f0df.png)
Something about the mixing means that all the models using Allison don't really change PSat untill H2O>3 wt%. However, a mixed model made out of Dixon-Moore and Dixon-Dixo (star symbols) follow Allison's spreadsheet very similarly. E.g., the weird behavoir of mixed models means, annoyingly, at the moment its still more accurate to use Dixon, or a Dixon-Moore hybrid, even though from the 1st figure, the carbon solubility is clearly wrong. 

The situation is even worse for a similar synthetic array, but instead with 5000 ppm. There is no change in VESIcal PSat despite variable H2O contents. The hybrids with Dixon also start show crazy behavoir but at least they are changing with H2O!
![image](https://user-images.githubusercontent.com/65668673/87315884-e3cf6f00-c51c-11ea-8674-fa3f15237e80.png)

I've looked into the differences between Lesne and the different H2O models, and it seems like the others aren't that bad. So i think it must be something to do with the mixing, rather than the water models not matching Allisons spreadsheet. E.g., for Etna, Lesne is almost identical to Shishkina. For the others there are bigger differences, but I also wouldn't necessarily expect the Etna Lesne line to be any more correct that these other ones. 
![image](https://user-images.githubusercontent.com/65668673/87316080-2e50eb80-c51d-11ea-91ed-0b3fb0a60bbd.png)

see Testing_Allison_et_al_2019

**Comment by simonwmatthews** [comment]
Hmm. This is odd. Does it change if you switch the order you define H2O and CO2 in? I.e.:
`mixed_model_Moore_sunset = v.MixedFluid({'H2O':v.MooreWater(),'CO2':v.AllisonCarbon(model_fit='thermodynamic', model_loc='sunset')})`
It *shouldn't* do, as the code should switch them in the root finder.

This might be related to the starting guess for the root finder, though I'm not sure why it would depend on which H2O model. I'll look into this. Is the code in the testing folder?

**Comment by simonwmatthews** [comment]
Also, those plots are looking AWESOME.

**Comment by PennyWieser** [comment]
Switching doesn't seem to do anything, yes, updated files in "test" folder

**Comment by simonwmatthews** [comment]
@PennyWieser this should be fixed now. Turned out the fugacity model was ignoring X_fluid and always returning the fugacity for the pure fluid only. I've also made the testing notebook compatible with my changes to the code.
