### ISSUE TITLE
Consistency typing up equations

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#108]
Hi all, I'm currently typing all the equations into the manuscript. There is, unsurprisingly, a lot of different notation. I think it would be best to partially standardize things so its easier for readers to follow. Would appreciate opinions on the options below. 
![image](https://user-images.githubusercontent.com/65668673/87545158-726bf980-c69f-11ea-87df-899eea1c4553.png)
![image](https://user-images.githubusercontent.com/65668673/87545462-e27a7f80-c69f-11ea-942d-f0016851bfe0.png)

**Comment by simonwmatthews** [comment]
My (totally unjustified) preferences are:
1. `x_\textrm{element}`
2. ln(...)
3. [CO2] though I think I prefer something like `w_\textrm{oxide}` to make it comparable with notation for mole fractions, though this might make the equations less intelligible.
4. I think [CO2 (ppm)] , though my preference is to use something like `w_\textrm{oxide}` to ubiquitously refer to a particular unit, with same caveat as for 3.

I don't *think* AGU have a style guide for this, unfortunately...

**Comment by kaylai** [comment]
Simon, is that LaTeX? It didn't parse here in github. What does `x_\textrm{element}` look like in practice? My LaTeX is rusty...

My also unjustified preferences are:

1. X<sub>element</sub>

2. ln(i)

3. [CO<sub>2</sub>] to be consistent with chemistry notation (where square brackets denote concentration). BUT, I think the ln operator gets parentheses. So, I usually do ln(CO<sub>2</sub>), where CO<sub>2</sub> itself is the variable corresponding to, for example, concentration in ppm that I then state in the text. For example:

>P = a &times; 2.255b + ln(CO<sub>2</sub>)
where P is pressure in bars, a and b are constants defined in Table X, and CO<sub>2</sub> is the concentration of CO<sub>2</sub> in ppm in the melt.

4. I'm a fan of the &times; symbol, although in my previous example I use a combo of the $times; symbol and just putting the number up against the variable, when they sort of mathematically go together.

I think that was mostly unhelpful! How about I can go through everything at the end and try and make sure it is all consistent?

**Comment by simonwmatthews** [comment]
Ah yes, that's LaTeX, I thought I would see if it did compile or not! \textrm{} will just typeset the contents in a normal font, rather than math font.

I missed the times symbol question! I *strongly* dislike '*' in manuscripts, but I think using both x and putting variables together are good for different situations. I tend to use x when I think there might be some ambiguity in just putting the symbols next to each other.
