### ISSUE TITLE
Calibration Check

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#11]
Write code to perform calibration check on all core calculations.

**Comment by kaylai** [comment]
Added some values for MagmaSat, but I'm not sure where the Warning gets implemented?

**Comment by simonwmatthews** [comment]
I think the best way of implementing the warning is in class Calculate(). Once the calculation is performed, it fetches the dictionary of dictionaries with the calibration check results. I think we could then write some code to process this output, and write out a warning. I'm happy to work on this, though I'll try to figure out some of the other issues first!

**Comment by kaylai** [comment]
Duplicate of #17
