### ISSUE TITLE
Calibration ranges should be <=, >= rather than <, >

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#111]
Simon, I thought of fixing this myself, but there's more than one way to do this so I figured I would check with you first. Currently the calibration range checks send out a warning if the value is equal to the minimum, but I think the behavior should require it to be less or greater than the minimum. 

For example, when passing 1 bar and 1200 oC to MooreWater():
```bash
The pressure is outside the calibration range of the Moore et al. (1998) water model, as 1.0 bar is not between 1.0 and 3000.0 bar. The temperature is outside the calibration range of the Moore et al. (1998) water model, as 1200.0 oC is not between 700.0 and 1200.0 oC. 
```

I think the solution is to change the < and > to <= and >= in the "DEFAULT CALIBRATION RANGE" section. If you agree, I can implement it, but the calibration checking has become quite complicated, so I didn't want to break everything by making the change without consulting you first.

**Comment by PennyWieser** [comment]
Hi @kaylai I literally started working on implementing the rest of these checks yesterday, and am changing this as part of that. Sorry I didn't push the code yesterday evening, as I hadn't finished! But now if say you enter 1200C for Shishkina, it doesn't return an error saying 1200C isn't between 1200C and X.

**Comment by kaylai** [comment]
Oh, excellent! Thanks! Please can you close this issue once the change is implemented? Cheers.

**Comment by simonwmatthews** [comment]
This change has been pushed now.
