### ISSUE TITLE
Streamlining major element checks

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#112]
Streamlining calibration checks to declutter warnings. Currently working with

`									 CalibrationRange('SiO2',[75,77],crf_BetweenLiu,'wt%','Liu et al. (2005) carbon',
													  fail_msg=crmsg_BetweenLiu_fail, pass_msg=crmsg_BetweenLiu_pass, description_msg=crmsg_BetweenLiu_description),
									 CalibrationRange('Na2O',[3.4,4.7],crf_BetweenLiu,'wt%','Liu et al. (2005) carbon',
													  fail_msg=crmsg_BetweenLiu_fail, pass_msg=crmsg_BetweenLiu_pass, description_msg=crmsg_BetweenLiu_description),
									 CalibrationRange('K2O',[3.6,5.7],crf_BetweenLiu,'wt%','Liu et al. (2005) carbon',                                                   
									 				  fail_msg=crmsg_BetweenLiu_fail, pass_msg=crmsg_BetweenLiu_pass, description_msg=crmsg_BetweenLiu_description),
									 CalibrationRange('Al2O3',[12.1,13.5],crf_BetweenLiu,'wt%','Liu et al. (2005) carbon',                                               
									 				  fail_msg=crmsg_BetweenLiu_fail, pass_msg=crmsg_BetweenLiu_pass, description_msg=crmsg_BetweenLiu_description),`

With the following

`def crf_BetweenLiu(calibval,paramval):
	return paramval >= calibval[0] and paramval <= calibval[1]
crmsg_BetweenLiu_pass = "The {param_name} ({param_val:.1f} {units}) is between {calib_val0:.1f} and {calib_val1:.1f} {units} as required by the calibration range of the {model_name} model. "
crmsg_BetweenLiu_fail = "The {param_name} content entered ({param_val:.1f} {units}) is outside the range of the calibration dataset of the {model_name} model ({calib_val0:.1f} to {calib_val1:.1f} {units})."
crmsg_BetweenLiu_faildetail= "As the Liu et al. model incorperates no term for compositional dependence, users must take extreme care when extrapolating this model to compositions which differ significantly from the haplogranites and rhyolites in the calibration dataset. These warnings are simply a guide; we suggest that users carefully compare their major element data to the calibration dataset to check for suitability."
crmsg_BetweenLiu_description = "The {model_name} model is calibrated for {param_name} between {calib_val0:.1f} and {calib_val1:.1f} {units}. "
`
But want specific warning only printed once if any of these checks fail

`crmsg_BetweenLiu_faildetail= "As the Liu et al. model incorperates no term for compositional dependence, users must take extreme care when extrapolating this model to compositions which differ significantly from the haplogranites and rhyolites in the calibration dataset. These warnings are simply a guide; we suggest that users carefully compare their major element data to the calibration dataset to check for suitability."`

**Comment by simonwmatthews** [comment]
Done.
