### ISSUE TITLE
Smoothing of isopleths leads to some odd lines in plot()

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#113]
Isopleths 2 and Isopleths 3 should intersect (0,0), which the calculated data does do. The output from MixedFluid.calculate_isobars_and_isopleths() shouldn't need smoothing, so perhaps the plot()) method could provide an option to smooth or not smooth? I could implement this, but thought I would check with you @kaylai first!

![image](https://user-images.githubusercontent.com/62933085/88069754-cbd59c00-cb69-11ea-9742-d70d392a5c47.png)

![image](https://user-images.githubusercontent.com/62933085/88069786-d4c66d80-cb69-11ea-8b48-dab318395ab0.png)

**Comment by PennyWieser** [comment]
I think this is also causing the problems I'm experiencing trying to get the Liu isobars to match their figure. It would be great to be able to output the raw isobar and isopleth values depending on the isopleth list the user enters as well as the smoothed ones to check you've given it enough points to get a decent smoothing? For most models, you could just enter more, but it would be particularly useful for Magmasat to see if you need to throw more computation power at it to get the right slope

**Comment by kaylai** [comment]
@simonwmatthews I *think* I've implemented this. Can you please share the code to generate the above plots so that I can test?

**Comment by simonwmatthews** [comment]
Not exactly the same code, but displays the same behaviour:
`bulk_comp = {'SiO2': 49.0,
            'TiO2': 1.13039100935431,
            'Al2O3': 15.868950708243196,
            'Fe2O3': 0.9299157089391744,
            'Cr2O3': 0.0,
            'FeO': 7.530168461039674,
            'MnO': 0.0,
            'MgO': 10.0559705373844,
            'NiO': 0.0,
            'CoO': 0.0,
            'CaO': 12.156051008287118,
            'Na2O': 2.704243106993772,
            'K2O': 0.3130313564365781,
            'P2O5': 0.0,
            'H2O': 0.0,
            'CO2': 0.0}
isobars, isopleths = v.calculate_isobars_and_isopleths(sample=bulk_comp, temperature=1200.0, pressure_list=[0,1000.0,2000.0], 
                                                       isopleth_list=[0.0,0.2,0.4,0.6,0.8,1.0], model='IaconoMarziano').result
v.plot(isobars=isobars,isopleths=isopleths)`

**Comment by kaylai** [comment]
Should be fixed now. I've rewritten the smooth_isobars_and_isopleths code so that its output matches that of calculate_isobars_and_isopleths and thus I call the smooth function inside of the calculate function (for MagmaSat only) if so desired.

I did this so that isobars and isopleths are automatically smoothed by default for MagmaSat models but not for others. When plotting, smoothing is set to False by default. Let me know if this fixes your problem!

Commit d2d3464e3d163c91c10b121ef8dab2649f473be9
