### ISSUE TITLE
Some Isobar discrepencies

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#117]
I can't get some isobars to match published figures. It seems a particular problem at high pressures, but a lot of it could be due to uncertainties in what the authors are actually showing in their figs. 

Example 1: Liu et al. 2005. Match is good vs. their Fig. 6b for orange and blue. Not perfect for the green line. I'm not sure what from the text what temp they used, so have shown 3. None of them quite match the curvature they show. Not really sure what else can vary, as Liu doesn't care about composition....E.g., while solid line works well at high H2O, isn't so good a fit at low H2O (bu arguably, still passes through their experimental data. Unless they've made a series of curves at different temps and taken the lowest bit?!
![image](https://user-images.githubusercontent.com/65668673/88556917-772a9900-d021-11ea-802c-42e0e0693561.png)

Example 2: Magmasat - works perfectly for Bishop tuff (although shows that even using a relatively large number of isopleths, the "smoothed" aren't a perfect fit to the data. 
![image](https://user-images.githubusercontent.com/65668673/88557376-0cc62880-d022-11ea-89a5-cfa35c0aeec6.png)
But MORB, discrepancy gets bigger with pressure.  I've played around a bit with normalization, Doesn't make nearly enough difference. So one option is that they didn't use the comp they said they did (this wouldnt be all that surprising, for their bishop tuff, the fig caption and figure show opposites of lower and upper),or based on the fact it happens in Liu too, is it something about higher pressures?
![image](https://user-images.githubusercontent.com/65668673/88559994-73007a80-d025-11ea-90b5-79a40a5ac5da.png)

Similarly, for Iacono-Marziano, their black and grey lines are for hydrous and anyhydrous coefficients. The VESIcal lines aren't too bad for 2000 bars (although not perfect), but pretty horrendous for 4000 bars
![image](https://user-images.githubusercontent.com/65668673/88563955-882bd800-d02a-11ea-90fe-d33e3b8afe24.png)

For their second plot, even worse if use Etna composition they say they calculated it for (Blue), Slightly better if use their Torre Alfino composition (red lines), but still nothing to write home about....

![image](https://user-images.githubusercontent.com/65668673/88568256-97ae1f80-d030-11ea-9412-9f897abfc31b.png)

**Comment by simonwmatthews** [comment]
For Liu, I noticed in the caption in the paper they mention some of the experiments were done for 98% H2O-CO2 fluid- perhaps the line is calculated for this too? i.e. 0.8*P. Would that match the discrepancy?

MagmaSat calculate_isobars_and_isopleths is driven by different code, so is likely a different issue.

For Iacono-Marziano... the isobars suggest the pure fluid values VESIcal is calculating are wrong.... but I thought the other tests suggested it was correct? If so, I'm not sure why the isobars are not the same... does the web-app allow isobars to be calculated?

**Comment by PennyWieser** [comment]
I've hand picked some points from the isobar diagram in their paper, and for that composition, entered those hand picked H2O and CO2 and ran them through their saturation pressure app online. Despite being the 4000 bar isobar, you get pressures which are not 4000. How to summarize this - do we want to actively call out that the isobars in the paper are wrong? Incase someone tries to use VESIcal to recreate their fig, realizes it doesnt match, and blame us? Perhaps just say we show saturation pressure and calc dissolved volatiles work, so does that gaurentee the isobars are also right?
![image](https://user-images.githubusercontent.com/65668673/88661898-2b372d00-d0d1-11ea-84fd-101fb0d0a1cd.png)

**Comment by PennyWieser** [comment]
@simonwmatthews Great spot, a factor of 0.98 for the upper one fixes Liu!
![image](https://user-images.githubusercontent.com/65668673/88663056-d5fc1b00-d0d2-11ea-916e-32da35f67734.png)

**Comment by PennyWieser** [comment]
To summarize this @kaylai and @simonwmatthews  - The remaining issues are 
1) MORB isobars in magmasat don't match - is there any reason a rhyolite composition would match but not a basaltic one? 
2) slight issues with dixon ones still related to #116

**Comment by kaylai** [comment]
@PennyWieser It does stand to reason that MELTS would do a better job of calculating a rhyolite than MORB, BUT I don't see how that would affect this, as we are essentially trying to make MELTS (MagmaSat) reproduce *itself*.  If normalization isn't causing the difference, I'm not sure what else could be. One other test we could do is to do some spot calculations in the MagmaSat app. Can you give me the composition and conditions you are using to create that figure? I can try running some points through the MagmaSat MacOS app and see if it matches the paper or VESIcal.

**Comment by PennyWieser** [comment]
@kaylai I vageuly remember from a course with Mark G a melts flow chart with what version to use being different for MORB and rhyolite in terms of the H2O model? (this was a long time ago so i may be remembering wrong), i was wondering if when they made their figure they used these slightly different paramterizations.

Sorry would have done this myself but the web app never converged for me!
Points along their 500 MPa isobar from a webplot digitizer
H2O  CO2
0.015, 0.260
0.842, 0.292
1.906, 0.310
2.935, 0.304
3.638, 0.290
1.396, 0.304
![image](https://user-images.githubusercontent.com/65668673/90665698-50d4d380-e244-11ea-8304-f5a877c429d8.png)


Its the MORB composition in the "isobars" tab here. From this table in the paper
![image](https://user-images.githubusercontent.com/65668673/90665115-84fbc480-e243-11ea-8b03-b4d2568204bc.png)


[Testing_Magmasat.xlsx](https://github.com/kaylai/VESIcal/files/5097909/Testing_Magmasat.xlsx)

**Comment by simonwmatthews** [comment]
Could this be related to using SWIM water vs MELTS water? I think SWIM is the default choice in ENKI?

**Comment by kaylai** [comment]
I ran those values through the MagmaSat app for MacOS. Here are the results. Note that it calculates Psats too low by up to 22 bars compared to the figure. That suggest that calculating these conditions at 500 bars would result in an isobar "above" the published one in the figure, which is what you're seeing Penny.

|  H2Omelt wt% | CO2melt wt%  | Psat (MamgaSat Mac App) bars |  Psat (VESIcal with MagmaSat) bars |
|---|---|---|---|
| 0.015  |  0.260 | 4878.04  |   4980 |
| 0.842  |0.292   |  4878.93 |   4930 |
|  1.906 |  0.310 | 4896.45  | 4910 |
| 2.935  | 0.304  | 4891.62 |  4860 |
| 3.638  | 0.290 |  4898.17 | 4840 |
| 1.396  | 0.304  |  4882.42 | 4910 |

My understanding is that the "MagmaSat" H2O-CO2 solubility model refers to ONE model, which is implemented in MELTS v 1.2.0. If they used a different model to calculate the isobar in that figure, it was not using "MagmaSat" proper.

The VESIcal calculations do not line up perfectly with the MagmaSat app, and I assume this is caused by the probably silly way that I wrote the code to find the satP, which involves coming down in P in steps and looking for an exsolved fluid phase, which is only as precise as your steps are small (and smaller steps = longer compute time).

In the end, I think it is OK that the VESIcal isobars don't match exactly, since some variation is to be expected due to the way I coded it. Since the MagmaSat app gives different results, I'd say that's even more reason not to assume the figure is correct.

**Comment by PennyWieser** [comment]
Thanks for checking @kaylai ! Yet to find a paper where all the isobar plots do actually match their online calculator ;) I'll just show the bishop tuff comparison in the testing, I think the case magmasat is coded correctly within rounding error is very strong based on the other tests.
