### ISSUE TITLE
Appending Pi, Pi* and SiO2-Pi onto Sat P outputs?

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#119]
@simonwmatthews I was wondering, how easy would it be to append a Pi* column onto outputs from Shishkina, and for Dixon, a Pi value (calculated from the full expression) and one from the Pi-SiO2 one? This would help because:
1) makes calibration plotting easier to let people see how bad volatilecalc is
2) means I could implement a calibration check which is basically Pi (full dixon)/Pi(volatileCalc), and if more than X% apart, spits out error.

**Comment by kaylai** [comment]
Penny, we could implement this via a 'verbose' return. Simon, is it possible to directly access, for example, ShishkinaCarbon().PiStar(sample)?

**Comment by simonwmatthews** [comment]
Yes, it should be straightforward. I've been meaning to do it, will try to do it tomorrow.

**Comment by kaylai** [comment]
By the way, Penny, you should be able to access the Shishkina PiStar method, for example, like so:

```python
#Create some sample named mysample

PiStar = v.ShishkinaCarbon().PiStar(mysample)

#Or have some ExcelFile object called myfile, and calc all PiStar values...

PiStar_vals = []
for index, row in myfile.data.iterrows():
    bulk_comp = {oxide: row[oxide] for oxide in v.oxides}
    PiStar_vals.append(v.ShishkinaCarbon().PiStar(bulk_comp)
```

**Comment by simonwmatthews** [comment]
Implemented. It will only be returned for saturation pressure calculations using the default Shishkina mixed fluid model.
