### ISSUE TITLE
IaconoMarzianoCarbon - FeO/Fe2O3

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#122]
@simonwmatthews  from looking at the code, it seems IM only uses FeO -In the web app you enter FeO*, and in their paper they say:

"We ignored in our treatment the possibility that ferrous and ferric iron may have different effects
on CO2 solubility; all iron is treated as ferrous iron and we
obtained a regressed parameter for FeO that is similar to
the one for MgO."

I interpret this to be that VESical  should do the calculations using FeOT not FeO. My initial testing didnt flag this up as i never had any Fe2O3 as the web app only does FeOt. Now, ive done an end member test of setting all FeO to Fe2O3, and the vesical pressure is different although the web app is the same

![image](https://user-images.githubusercontent.com/65668673/91029597-e2529580-e5f6-11ea-953b-e49e04443aa2.png)

On a related note, would  a calibration check for FeOT just be:

									 CalibrationRange('FeOt',[0,14.7],crf_Between,'wt%','IaconoMarzianoCarbon',
													  fail_msg=crmsg_BC_fail_ShC1, pass_msg=crmsg_BC_pass, description_msg=crmsg_Between_description),                   

it doesnt seem to do anything.

I've sent you an email of the code with all the cali checks so far, if you could merge them that would be amazing.

**Comment by simonwmatthews** [comment]
There's no straightforward way of having the calibration check use FeOt- as it should just be 'entered' as FeO by the time the solubility calculations are being performed. One way of dealing with it in the calculation would be to replace FeO with FeO + Fe2O3*constants, but that won't help with the calibration range.

I'll try to get the merge done later today.

**Comment by PennyWieser** [comment]
I think for the calc it defo needs to be FeO+Fe2O3*0.8998 as that is how the web app do it, and they do say they treat all Fe as FeT. This will be importnat for some model comparisons too

**Comment by simonwmatthews** [comment]
I've included Fe2O3 in the calculations, but it won't be included in the calibration checks. An alternative way to do this would be to reinstate the default sample preprocessing and have Fe2O3 + FeO -> FeOt for the IaconoMarziano models. This sort of thing was what I originally had in mind for the preprocessing step.

**Comment by PennyWieser** [comment]
Hi Simon, Sat P now match web app for f Fe3+-bearing melts! I'll leave it to you to decide best way to set up calibratoin checks, as I have no real idea what is easier!
