### ISSUE TITLE
calculate_dissolved_volatiles for carbon models returns zero

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#125]
I've been trying to use calculate_dissolved_volatiles to, say, calculate how much CO2 is dissolved in a given composition at 5000 bars (For XH2O=0) for the companion paper. 

It seems for CO2-only models (e.g., Allisons, Dixon, Liu) - the following just returns 0
`SampleName = 'Etna1'
bulk_comp = myfile_Ptest_CO2_Etna.get_sample_oxide_comp(SampleName)
Calc5000_Allison_Etna=v.calculate_dissolved_volatiles(sample=bulk_comp, temperature=1200, pressure=5000, model='DixonCarbon',
                                X_fluid=0, verbose=True).result`

But H2O-only models with X_fluid=1 return meaningful. Is this something fundamental about the way calculate_dissolved_volatiles works? I can share a script if not.

**Comment by simonwmatthews** [comment]
For pure fluid models X_fluid is always the the mole fraction of that volatile phase. So for the above, you're actually setting XCO2=0. For the mixed fluid models, passing a float (rather than a list or array etc) assumes that its XH2O, as a shortcut. If you want the pure fluid behaviour you can just ignore the X_fluid variable.

**Comment by PennyWieser** [comment]
That makes sense thanks simon!

**Comment by kaylai** [comment]
It seems to me that no one would ever want to pass X_fluid=0 to a pure fluid model. Should we return a warning message for this case? I can see why it is confusing, since X_fluid means XH2Ofluid in most cases (mixed and H2O-only models).

**Comment by simonwmatthews** [comment]
The pure fluid model may be called with Xfluid=0 when used in a mixed-fluid model, so the warning would have to be suppressed in that instance. Really, I think its unlikely that anyone would be using Xfluid for a pure fluid model anyway... its mostly there for using with the MixedFluid object.

**Comment by PennyWieser** [comment]
Maybe we should just specify in the manuscript bit about calc_dissolved_volatiles inputs exactly what X_fluid means with the caveat of CO2-only models
