### ISSUE TITLE
No warning given if user passes bad model name

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#126]
At least in batch calculation mode, if a user passes a non-existent model (e.g., as a typo like "AllisnCarbon"), the model runs and reports data back with an error message. In the model column, it shows the model name given by the user, even if that doesn't match a real model name. I think we should flag this and give a warning that the model does not exist.

Solution:
Implement checks (if model not in default_models) and print warning in returned data and as w.warn("message") letting the user know that a bad model name was passed.

**Comment by simonwmatthews** [comment]
Implemented.
