### ISSUE TITLE
Common Pitfalls or Pro Tips section on ReadTheDocs

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#130]
Add a page with common pitfalls or pro tips such as:

- Always check that your data imported correctly by printing myfile.data. If columns weren't read correctly (e.g., your 'SiO2' column was actually written like 'SiO_2' or something not parsed by VESIcal), then VESIcal will think your SiO2 concentration is 0 wt%. If running MagmaSat, this can cause VESIcal to just hang forever and never give output (or crash the kernel if you are running in jupyter)
- Tips on when to normalize data
- Tips and examples on how to edit/modify/copy ExcelFile objects
- Tips and examples on how to work with ExcelFile objects and ExcelFile.data objects

**Comment by PennyWieser** [comment]
Write about the MagmaSat bug - where if it fails on a calculation, it prints the remaining PSats for the excel file as zeros - and you have to restart the kernel to get it to perform any more calculations - I think we choose this as a  lesser of 2 evils - as before you lost all the calculations it had got too. Perhaps we can raise an issue on github and link to that in the "pro tips/pitfalls" bit.

**Comment by PennyWieser** [comment]
Add normalization pitfalls -> E.g. literature data which has renormalized majors to 100% Anhydrous - in very hydrous systems (e.g., arcs) - can cause reasonably big discrepancies (as system total ends up at like 106-108 wt%)

**Comment by PennyWieser** [comment]
> Write about the MagmaSat bug - where if it fails on a calculation, it prints the remaining PSats for the excel file as zeros - and you have to restart the kernel to get it to perform any more calculations - I think we choose this as a lesser of 2 evils - as before you lost all the calculations it had got too. Perhaps we can raise an issue on github and link to that in the "pro tips/pitfalls" bit.

Going to make a you tube video about this using the Blundy MSH example

**Comment by kaylai** [comment]
We have documented all of this and more, so I'm closing this issue.
