### ISSUE TITLE
Sample._composition to Sample.composition?

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#133]
I think people will want to access the sample composition frequently. Is it okay to change the Sample._composition object to be called simply Sample.composition (e.g., without the underscore)?

**Comment by simonwmatthews** [comment]
Users should get the composition of the sample using the `Sample.get_composition()` method, not with `Sample._composition` directly. This is to avoid accidentally changing the composition of the sample- or overwriting the information during conversion. If you use `Sample.get_composition()` the composition will be returned as wt% oxides, unless you have specifically told the object to use a different unit as default. If you want just one oxide, you can use `Sample.get_composition('CO2')`. To get other units, or normalize the return in different ways you can specify this in the `get_composition()` call. The reason I named the property `_composition` was to try to make it clear that this variable should only be called by methods within the class.

We could add a shorter version of the call though- perhaps have something like `Sample.gc()` or `Sample.composition()`, `Sample.getcomp()`?

**Comment by kaylai** [comment]
Sounds good! I hadn't realized you already set up get_composition! Perhaps to be consistent with the BatchFile class, we could have an attribute Sample.data that would return Sample.get_composition()? It's redundant, but I think it's good to have the batch methods similar to the singlesample methods whenever possible.

**Comment by kaylai** [comment]
Instead of change the Sample class I have added a new method to BatchFile called get_composition. Users can now return the compositional information (excluding other non-compositional information for each sample) for a BatchFile object as a pandas dataframe using BatchFile.get_composition(). This takes the same arguments as Sample.get_composition()
