### ISSUE TITLE
Calculate doc string: sample type?

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#136]
With the new sample_class, do the Calculate subclasses (like calculate_dissolved_volatiles(Calculate)) take in a sample_class.Sample object or is it still dict/pandas series?

I think it's the former now, but I didn't want to update the doc string if that was wrong!

**Comment by simonwmatthews** [comment]
Ooops! Yes- they take in a Sample class object now. Sorry, I should have updated the docstrings. I think I updated them correctly elsewhere in the module...

**Comment by kaylai** [comment]
Fixed :)

commit: a234d9bc67623803b4feaec0c3df5143ac7f45fd
