### ISSUE TITLE
Changes in Liu outputs

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#138]
In the testing notebook for Liu (see new folder in Dev./VESIcal/Calibration/Testing_March2021/)

Test 1 used to return this (VEsical version 6 months ago)
![image](https://user-images.githubusercontent.com/65668673/111623039-c9534100-87e1-11eb-990c-c0ddb73875f6.png)

Now it returns this?
![image](https://user-images.githubusercontent.com/65668673/111623063-ceb08b80-87e1-11eb-86a0-f8b84425cebe.png)
Numbers the same where it gives them, but returns  A LOT more Nans. 

Does the regardless of whether you specify Liu or LiuWater in both scripts.

**Comment by simonwmatthews** [comment]
I don't think this is the solution, but just to check it isn't something this simple... Can you change `input_type='wtpercent'` to `input_type='wtpt_oxides'` and try running again?

**Comment by PennyWieser** [comment]
Sadly, that doesnt change anything.

**Comment by kaylai** [comment]
@simonwmatthews it looks like a negative value for pressure is being passed to Liu's root_saturation_pressure() method. Did we run into this issue before? Not sure how to handle it or why this is happening now when it didn't before.

**Comment by PennyWieser** [comment]
At least for this exact input, it ran fine in the old version of VESical. I never encountered this with any other Liu things either, but that doesnt mean it wasn't there and I just never found an input that tripped it up.

**Comment by simonwmatthews** [comment]
That suggests its finding a non-zero solubility at zero pressure, which is odd. If you try calculating the solubility of H2O for that sample at 0 bar what happens?

At the moment the root finder doesn't know that only certain values of pressure are sensible, it just takes a starting guess. One option would be to define a range in which it should look for a solution. This is how some of the other models run the root finder. However, if there is no root at P > 0 bar, then this won't solve the problem...

**Comment by kaylai** [comment]
Weirdly, if I run the sample by itself as a single sample object, it works just fine. That tells me the error is probably in batchmodel. I'll look deeper.

**Comment by kaylai** [comment]
Running the first sample by itself in a single sample calculation returns nan for the saturation pressure. 

calculate_dissolved_volatiles at pressure=0 gives:
{'H2O_liq': 0.0, 'CO2_liq': 0.0}

**Comment by kaylai** [comment]
@simonwmatthews if I change the initial guesses on root_scalar (line 166 in Liu.py) to be x0=1.0, x1=2.0, then it works.

I arbitrarily chose these values as it is what we are using for the IaconoMarziano model. Should we leave these as 1 and 2 instead of 10 and 200???

**Comment by simonwmatthews** [comment]
I think that's fine. I'm always slightly uncomfortable about how arbitrary the initial guesses are, but as long as it works... I guess the other option is writing our own custom algorithms for solving the problem.
