### ISSUE TITLE
Speed of Iacono-Marziano

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#144]
Simon, when might you have a chance to try to speed this up? MArk wants me to make the jupyter notebooks for the companion paper available , but at the moment to address how slow IM is, I've had to do a lot of pickling and intermediate saving to stop the notebooks crashing/taking hours to run, which isn't ideal for sharing these. Just let me know so I know when to start tidying them all up!

**Comment by simonwmatthews** [comment]
I thought @kaylai had fixed this? Are you running the latest version of the code?

**Comment by PennyWieser** [comment]
I'm using the version on pip 0.9.10?
It might be a bit faster than it was, but it is still slower than magmasat, while it used to be comparable to dixon.
![image](https://user-images.githubusercontent.com/65668673/114277583-9a934980-99e0-11eb-8a85-62c309b15080.png)

Code
`my_sample1 ={'SiO2':  47.4,
 'TiO2':     1.01,
 'Al2O3':    17.64,
 'Fe2O3':     0.89,
 'FeO':       7.18,
 'MgO':      7.63,
 'CaO':      12.44,
 'Na2O':      2.65,
 'K2O':       0.03,
 'H2O':       3.47,
 'CO2':       0.05}

%%time
SatP = v.calculate_saturation_pressure(sample=my_sample1, temperature=750).result

%%time
SatP = v.calculate_saturation_pressure(sample=my_sample1, temperature=750, model="IaconoMarziano").result

%%time
SatP = v.calculate_saturation_pressure(sample=my_sample1, temperature=750, model="Dixon").result
`

**Comment by PennyWieser** [comment]
Again, arg, sorry this was because for some reason it was using an old version despite saying it was using the new one
Sorry
