### ISSUE TITLE
Inconsistent documentation re. sample class

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#145]
I'm a little confused by the new way to define a sample (Seems like the bit of code that has changed the most). 
I have got the latest version through pip. While the read the docs calls it "v.Sample", I get an eror unless I call it "v.sample".

Also, from the read the docs I intepreted that I would first have to do:
mysample = v.sample({'SiO2': 77.5,
         'TiO2': 0.08,
         'Al2O3': 12.5,
         'Fe2O3': 0.207,
         'Cr2O3': 0.0,
         'FeO': 0.473,
         'MnO': 0.0,
         'MgO': 0.03,
         'NiO': 0.0,
         'CoO': 0.0,
         'CaO': 0.43,
         'Na2O': 3.98,
         'K2O': 4.88,
         'P2O5': 0.0,
         'H2O': 5.5,
         'CO2': 0.05})

Then 

isobars, isopleths = v.calculate_isobars_and_isopleths(sample=mysample,
                                    temperature=1200,
                                    pressure_list=[1000],
                                    isopleth_list=[0]).result

But this throws the error "'sample' object has no attribute 'copy'
It only works if I get rid of  v.sample when I define th composition

Has this been changed since the documentation was written? Or am I just being thick?

**Comment by kaylai** [comment]
The Sample class has to be capitalized! You can name the variable whatever you want, but construct it via v.Sample()

**Comment by PennyWieser** [comment]
Okay, for some reason my VESIcal wasn't updating on the enki server, sorry about that. Ignore the other issues for now, i'll see if they are old version issues.
