### ISSUE TITLE
Notebooks with old version of commands are still around

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#157]
There are some notebooks that people are accessing and using which used the pre-revision version of VESIcal. One of the big changes was the switch from `ExcelFile` to `BatchFile`. If these notebooks are part of the published record, then there's not much we can do, but we can perhaps provide easier access to updated versions. When I find some time I will track down where these notebooks are coming from.

**Comment by simonwmatthews** [comment]
I think this is coming from the notebooks linked to the youtube tutorials.

**Comment by PennyWieser** [comment]
Hi Simon,
Yup, the ExcelFile thing happened after I made these videos....
Not sure if its enough just to change the notebook over or whetehr I should remake the video. @kaylai how did you get a box to pop up in the other old videos to just say "its now called ExcelFile"

**Comment by simonwmatthews** [comment]
I think it would be good to avoid recreating the videos! As you say, a pop-up box and adjusted notebooks would be the ideal solution I think.

**Comment by PennyWieser** [comment]
Okay actually now I'm super confused. I've got these the wrong way around, ExcelFile is the old one (duh).

So the ones still using ExcelFile are 
1) Kayla's video here: https://www.youtube.com/watch?v=F9czuzPc5Kg&t=143s

@kaylai I've noticed the files for the second tutorial on read the docs aren't there - 
![image](https://user-images.githubusercontent.com/65668673/149677538-5d666acf-dae4-4c5d-96e1-6d05dee18551.png)

As you do your read-the-docs very differently from how I've done mine, I dont want to mess it up, i've attached the files here instead so you can add when you have a chance

Just checked all the videos I have made say BatchFile

**Comment by simonwmatthews** [comment]
Thanks for following this up Penny. I might have some time later in the week to work on this.

**Comment by kaylai** [comment]
> Hi Simon, Yup, the ExcelFile thing happened after I made these videos.... Not sure if its enough just to change the notebook over or whetehr I should remake the video. @kaylai how did you get a box to pop up in the other old videos to just say "its now called ExcelFile"

For those videos that I updated, I literally just edited the video in iMove or something and added those text boxes at the appropriate times, then reuploaded the video to YouTube.

@PennyWieser specifically, what files need to be linked along with that video? I'll add links.

**Comment by kaylai** [comment]
> I think this is coming from the notebooks linked to the youtube tutorials.

Which ones? I thought I updated all of them.

**Comment by PennyWieser** [comment]
Ahh okay so perhaps its from https://www.youtube.com/watch?v=F9czuzPc5Kg&t=143s - Because for me, an add box was covering up the box saying the command had changed. Maybe thats what people are finding?!

Re file linking - Intro 2: Sat Ps, Dissolved Volatiles, Degassing paths, Isobars video needs linking to https://github.com/kaylai/VESIcal/blob/master/You%20Tube%20Examples/Introduction_Example_different_functions.ipynb

**Comment by simonwmatthews** [comment]
Just dumping this info here (will follow up later, or maybe it will make sense to someone...). One of the old notebooks was found by a user on the ENKI server from:
Notebooks  --> VESIcal  --> Tutorials --> ReadtheDocs

**Comment by kaylai** [comment]
> Ahh okay so perhaps its from https://www.youtube.com/watch?v=F9czuzPc5Kg&t=143s - Because for me, an add box was covering up the box saying the command had changed. Maybe thats what people are finding?!
> 
> Re file linking - Intro 2: Sat Ps, Dissolved Volatiles, Degassing paths, Isobars video needs linking to https://github.com/kaylai/VESIcal/blob/master/You%20Tube%20Examples/Introduction_Example_different_functions.ipynb

Link has been added! Commit fad0b15a4cd90063bfc0b20f5c6d5acfc496b93a

**Comment by kaylai** [comment]
> One of the old notebooks was found by a user on the ENKI server from: Notebooks --> VESIcal --> Tutorials --> ReadtheDocs

@simonwmatthews Did someone tell you this is where they found the notebooks? I'm confused, because I don't see a Notebooks folder on the ENKI server. It might have been something they uploaded to their own ENKI home folder?

**Comment by kaylai** [comment]
Was this ever resolved?

**Comment by kaylai** [comment]
I recently found some documentation notebooks here in the VESIcal repo that had the old ExcelFile() class. I fixed all of those now so will consider this closed.
