### ISSUE TITLE
Verbose argument doesn't propagate in BatchFile calculations

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#159]
If someone is calculating the equilibrium fluid composition at a specified pressure, the BatchFile method won't return mass of fluid etc in the DataFrame. Probably the best thing to do is to run calculations in verbose mode always when using BatchFiles. I also think the models I coded won't supply this information at all. I should be able to find time to fix this soon, but I'm tagging you Kayla just so you're aware, or maybe there's something I've missed!

**Comment by kaylai** [comment]
Fixed! At least for calculate_equilibrium_fluid_composition(). This is updated in v1.0.3, commit 4eaa1dfd05a70b19e98c27ec718b4852e56904bd
