### ISSUE TITLE
Write code for calibration_check

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#17]
Should check pressure, temperature, AND composition! We could write this to simply warn the user to please not use the models outside of their range (but allow them to). At some extreme point we can make the code simply refuse to do the calc! Thoughts?

**Comment by simonwmatthews** [comment]
I think we could implement warnings if the parameters aren't in the calibration range (https://docs.python.org/3.1/library/warnings.html). We could do this in the main methods using the outputs from the check_calibration method calls? You can then set the warnings to either just be warnings, to be ignored entirely, or to result in an error.

**Comment by kaylai** [comment]
Implemented for MooreWater. Simon, do you have more of these to implement? I still need to do MagmaSat.

**Comment by kaylai** [comment]
Is it possible to have the warning come up _before_ the calculation is performed? In some cases, it might be nice to warn folks in this way, because sometimes the model (MagmaSat) will not converge on a solution if the parameters are crazy. So if someone puts T=200 and they meant to put T=2000, would be cool if the warning would come up before the calculation started, otherwise the code will just hang forever.

**Comment by simonwmatthews** [comment]
I think I've done all the checks for P and T. Some don't have P and T bounds as they didn't state any in the papers (see my comment on a different issue about two levels of warning- stated bounds and calibration range bounds).

**Comment by simonwmatthews** [comment]
> Is it possible to have the warning come up _before_ the calculation is performed? In some cases, it might be nice to warn folks in this way, because sometimes the model (MagmaSat) will not converge on a solution if the parameters are crazy. So if someone puts T=200 and they meant to put T=2000, would be cool if the warning would come up before the calculation started, otherwise the code will just hang forever.

I think this is a good idea for the computationally intense methods. The reason I implemented it following calculation is so that it could check the calculation result too. A pre-check can easily be implemented though, and I'll do this when I update the calibration checking framework.

**Comment by simonwmatthews** [comment]
When I say computationally intense- I guess I mean (all?) Magmasat calculations, and generally the degassing paths calculations. The 'simpler' methods will just return an error rather than hang. On the other hand, we could implement pre- and post- checks uniformly, then incorporate this into any error reporting. Perhaps that's simpler (and better!).

**Comment by kaylai** [comment]
I like either option: pre-checks only for intense methods or pre-checks for all. Thanks for implementing!

**Comment by kaylai** [comment]
I think this implementation is complete, so I'm closing this issue. If I'm wrong, and more work needs to be done, please re-open this issue or create a new one and specify what needs doing.
