### ISSUE TITLE
Printing Duan Driver to Console

### ISSUE THREAD

**Issue by fboschetty** [kaylai/VESIcal#183]
I'm running calculate_saturation_pressure() for a batch of several thousand samples.
Upon each execution VESIcal prints multiple lines to screen, each relates to Duan Driver, I'm assuming relating to an inbuilt function. See the attached screenshot for info.

<img width="1271" alt="Screenshot 2024-03-06 at 18 47 44" src="https://github.com/kaylai/VESIcal/assets/64596942/3a64da00-267a-4b1b-a21a-dd6ffe33a4c2">

I'm using the most recent version of VESIcal 1.2.5.
I just managed to get it all to work installing thermoengine locally on an apple silicon machine so there's a chance it relates to this.

Many thanks,

Felix

**Comment by kaylai** [comment]
Hi Felix, thanks for flagging this. I have looked into silencing the Dean diver printing before, and I can't recall if I had much success. I think the answer is unfortunately that this is embedded within MagmaSat (thermoengine), and that I was unable to silence these. I'll have another look at this and do some research into how to pythonically handle this (if we can). If you know of a way to silence warnings from an imported library that might help this, please let me know!

**Comment by kaylai** [comment]
Followup, can you please provide a minimum working example of the code to generate this printout, so that I can test against it? Thanks!

**Comment by fboschetty** [comment]
```python
import VESIcal as v

Path = "/Users/felixboschetty/Documents/Spyder/Melt Inclusion CO2/VESICal Prep/VESICal_Prep_1.xlsx"
myfile = v.BatchFile(Path)
data = myfile.get_data()

satPs = myfile.calculate_saturation_pressure(temperature="T")
myfile.save_excel("myoutput.xlsx", calculations=[satPs])

[VESICal_Prep_1.xlsx](https://github.com/kaylai/VESIcal/files/14515647/VESICal_Prep_1.xlsx)

**Comment by kaylai** [comment]
Funny story! I found that @simonwmatthews and I worked on stopping duanH2O driver messages from printing to the console for VESIcal version 1.0.4. I'm not sure if we just didn't catch them all at the time or if something has changed now such that our fix no longer works. I implemented a new fix that does work with the example from @fboschetty, and I've asked Simon to review a pull request for that code before merging it with the main branch.

Felix, if you are comfortable doing so, it would be a great help to us if you could check out the silenceThermoEnginestdout branch and confirm that you don't see the duanDriver messages anymore (and that nothing else is broken). My way of doing this is creating a conda env without VESIcal installed and then running my script that imports VESIcal from the top level of the VESIcal folder so that it just pulls that version instead of a pip installed one.

**Comment by fboschetty** [comment]
Hi @kaylai,

I'm happy to try, but i'm not sure how I should go about installing the different branch. I'm also hesitant to mess with my currently working environment with a working version of ThermoEngine.

Thanks,

Felix

**Comment by simonwmatthews** [comment]
Sorry for the delay in getting back to you on this! Our previous fix worked for a short time, or maybe a particular install, but seemed to break again pretty quickly. I have been meaning to take a look at what is going on, so I am very happy to see this! I will take a look at the pull request this week.

**Comment by kaylai** [comment]
@fboschetty No problem. I'd like to do a bit more testing before pushing the new version to pip. Once @simonwmatthews has a chance to take a look, that ought to do it.

**Comment by kaylai** [comment]
My latest fix doesn't seem to be working after all. I'm doing some more tests to see if I can get rid of these super pesky Duan driver errors...

**Comment by kaylai** [comment]
Unfortunately I have to reopen this issue. It appears my fix broke magmasat calculations for some people, and is throwing a `UnsupportedOperation: fileno` error. This seems to be related to the `fileno()` command[ breaking in different environments](https://stackoverflow.com/questions/31080829/python-error-io-unsupportedoperation-fileno). I don't quite understand why. I'm going to see if I can fix this asap.

**Comment by kaylai** [comment]
When running on the ENKI Jupyter server, this error is thrown when running a magmasat calculation:

```python
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
Cell In [5], line 1
----> 1 Sat_P_MagmaSat_sample=v.calculate_saturation_pressure(sample=degassed_sample, temperature=1180)
      2 print(Sat_P_MagmaSat_sample.model_name)
      3 print(Sat_P_MagmaSat_sample.result)

File /opt/conda/lib/python3.9/site-packages/VESIcal/calculate_classes.py:54, in Calculate.__init__(self, sample, model, silence_warnings, **kwargs)
     50     self.model = model
     52 self.sample = sample
---> 54 self.result = self.calculate(sample=self.sample, **kwargs)
     55 self.calib_check = self.check_calibration_range(sample=self.sample,
     56                                                 **kwargs)
     58 if self.calib_check is not None and silence_warnings is False:

File /opt/conda/lib/python3.9/site-packages/VESIcal/calculate_classes.py:373, in calculate_saturation_pressure.calculate(self, sample, **kwargs)
    372 def calculate(self, sample, **kwargs):
--> 373     satP = self.model.calculate_saturation_pressure(sample=sample,
    374                                                     **kwargs)
    375     if isinstance(satP, dict):
    376         return {key: np.float64(value) for key, value in satP.items()}

File /opt/conda/lib/python3.9/site-packages/VESIcal/models/magmasat.py:651, in MagmaSat.calculate_saturation_pressure(self, sample, temperature, verbose, **kwargs)
    648 pressureMPa = 2000
    650 # Check if saturated at 2000 MPa (rare, for deep samples)
--> 651 with stdout_redirected():
    652     output = self.melts.equilibrate_tp(temperature, pressureMPa,
    653                                        initialize=True)
    654 (status, temperature, pressureMPa, xmlout) = output[0]

File /opt/conda/lib/python3.9/contextlib.py:119, in _GeneratorContextManager.__enter__(self)
    117 del self.args, self.kwds, self.func
    118 try:
--> 119     return next(self.gen)
    120 except StopIteration:
    121     raise RuntimeError("generator didn't yield") from None

File /opt/conda/lib/python3.9/site-packages/VESIcal/models/magmasat.py:33, in stdout_redirected(to)
     20 @contextmanager
     21 def stdout_redirected(to=os.devnull):
     22     '''
     23     import os
     24 
   (...)
     31                 17954769#17954769')
     32     '''
---> 33     fd = sys.stdout.fileno()
     35     def _redirect_stdout(to):
     36         sys.stdout.close()  # + implicit flush()

File /opt/conda/lib/python3.9/site-packages/ipykernel/iostream.py:311, in OutStream.fileno(self)
    309     return self._original_stdstream_copy
    310 else:
--> 311     raise io.UnsupportedOperation("fileno")

UnsupportedOperation: fileno
```

My best guess is this is related to `sys.stdout.fileno()` being a file-like object and that Jupyter handles files differently, particularly in Jupyter hub. I'm not really sure, to be honest. I will test other code that might work on all systems, but if someone else has any ideas, I'm all ears.

**Comment by kaylai** [comment]
Unfortunately for now I am going to have to revert back to our old code and stop trying to silence DuanDriver warnings for now. I've made an [Issue on the Thermoengine GitHub](https://gitlab.com/ENKI-portal/ThermoEngine/-/issues/28) asking them to either remove or allow silencing of the DuanDriver warnings. Hopefully they will be receptive to this request. I'm going to close this for now since there is nothing we can do at the moment.
