### ISSUE TITLE
Non-reproducible Pressures for example dataset

### ISSUE THREAD

**Issue by fboschetty** [kaylai/VESIcal#185]
Hi all,

So I've calculated saturation pressures of the example dataset using the default model, magmasat, and found that the calculated pressures do not match those shown in https://vesical.readthedocs.io/en/latest/ex_satP.html#for-an-entire-dataset.
They are close, less than 100 bars out, but I'm not sure whether I should be concerned or not. I've attached the output as a spreadsheet.

I'm using VESIcal 1.2.5..

Thanks,

Felix

[test_out.xlsx](https://github.com/kaylai/VESIcal/files/14576681/test_out.xlsx)

**Comment by fboschetty** [comment]
Here's my code and the input file.

```python
import VESIcal as v
Path = "/Users/felixboschetty/Documents/Spyder/Melt Inclusion CO2/VESICal/example_data.xlsx"
myfile = v.BatchFile(Path)
data = myfile.get_data()

satPs = myfile.calculate_saturation_pressure(temperature=925.)
myfile.save_excel("test_out.xlsx", calculations=[satPs])
```
[example_data.xlsx](https://github.com/kaylai/VESIcal/files/14576747/example_data.xlsx)

**Comment by kaylai** [comment]
Hi all, I'm finding the same issue with some other reruns of data from the manuscript I am doing. Similarly to Felix's findings, the pressures I'm getting are close but not exactly the same. I'm going to run everything again using the version of the code that we snapshotted for the publication of the manuscript (v.1.0.1) and then with the current version and see if the change happened in between those times.

We did tweak the normalization behavior during review, so maybe it's that?

**Comment by kaylai** [comment]
Hi all, this is indeed an issue where we had run the notebooks with an earlier version of the code and generated docs from those old runs. I've fixed those now as well as adding in new testing routines to ensure that the content of the manuscript and docs match the most current version of VESIcal. Closing this issue as I have merged into main and docs are recompiled. Thanks for flagging this!
