### ISSUE TITLE
Why does calculate_degassing_path stop at 100 bars by default?

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#192]
I just discovered that in `model_classes.MixedFluid.calculate_degassing_path()` we have set the `final_pressure` argument to 100.0 by default. This is in contrast to the documentation, which states the default is 1 bar. I did a test, and the degassing path does indeed stop at 100 bars. Is this a mistake that's been hidden in there for a long time?? @simonwmatthews do you remember?

The call structure:
```python
def calculate_degassing_path(self, sample, pressure='saturation',
                                 fractionate_vapor=0.0, final_pressure=100.0,
                                 steps=101, return_dfs=True,
                                 round_to_zero=True, **kwargs):
```

The relevant documentation (doc string):
```
final_pressure         float
            The final pressure on the degassing path, in bars. Ignored if a
            list or numpy array is passed as the pressure variable. Default is
            1 bar.
```

Reproducible code on VESIcal v 1.2.7:
```python
import VESIcal as v

composition = v.Sample({"SiO2": 52.2553404524503,
                "Al2O3": 17.846286510119086,
                "TiO2": 0.9692238504763523,
                "FeO": 10.898505868900829,
                "MgO": 5.389473588157527,
                "CaO": 8.819968147407465,
                "Na2O": 2.939609172692212,
                "K2O": 0.4817499825535557,
                "P2O5": 0.22076362230278734,
                "MnO": 0.1790788049398374,
                "H2O": 4.5,
                "CO2": 0.33
                })

degassing_path_IM = v.calculate_degassing_path(composition, temperature=1030, model="IaconoMarziano").result

print(degassing_path_IM.tail())
```

Result printed to terminal:
```
     Pressure_bars   H2O_liq   CO2_liq    H2O_fl    CO2_fl  FluidProportion_wt
96      284.566879  1.290003  0.000651  0.961267  0.038733            3.539345
97      238.425159  1.167935  0.000519  0.962472  0.037528            3.661546
98      192.283440  1.035812  0.000397  0.963687  0.036313            3.793792
99      146.141720  0.889762  0.000285  0.964932  0.035068            3.939954
100     100.000000  0.722483  0.000183  0.966245  0.033755            4.107334
```

**Comment by simonwmatthews** [comment]
I believe it is a mistake- I spotted this a little while ago- and I think I fixed it in the dev version that I still need to finalise. I can maybe try to isolate this from the problematic parts of the dev version and submit a pull request for just that?

**Comment by kaylai** [comment]
Sure, please do! Otherwise, I can easily make the change, test, and do a pull request if that's easier.

**Comment by kaylai** [comment]
I thought there was already an option for specifying final pressure? How many commits behind is the dev version; maybe that's the issue? 

I was thinking the best solution would be to set the default value to 1 bar and do some testing along side on degassing paths to ensure the results we are getting are consistent and not throwing errors, then those can be added to the testing suite. Speaking of which, I'm making some major additions to the testing suite now, and in that I've set the default final pressure to 1, but I haven't added unit tests to cover the degassing paths (except some in the manuscript). I have a pull request that I"ll submit soon as well.

**Comment by kaylai** [comment]
I'm going to go ahead and merge my pull request that does have the fix, where all I did was change the default value from 100.0 to 1.0. It does, however, also include those updates to testing routines. I'll consider this issue closed with that PR.

**Comment by kaylai** [comment]
Closed with merge of PR 193
