### ISSUE TITLE
Unittests failing on my machine

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#195]
I have been trying to bring the dev branch into line with main before submitting the pull request. When I started to run the unittests python would crash with a segmentation fault. I installed the main branch directly, and though the unittests run fine, they have the following failures:

======================================================================
FAIL: test_dissolved_volatiles_sample_10star (test_manuscript.TestManuscriptCalculations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/simonm/repos/VESIcal/tests/test_manuscript.py", line 241, in test_dissolved_volatiles_sample_10star
    self.assertDictEqual(result, self.tenstar_verbose_diss_vol)
AssertionError: {'H2O[15 chars]30386766, 'CO2_liq': 0.0638470697174877, 'XH2O[91 chars]9362} != {'H2O[15 chars]30386574, 'CO2_liq': 0.0638470697446765, 'XH2O[92 chars]0492}
Diff is 702 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_equilibrium_fluid_sample_10star (test_manuscript.TestManuscriptCalculations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/simonm/repos/VESIcal/tests/test_manuscript.py", line 267, in test_equilibrium_fluid_sample_10star
    self.assertDictEqual(result, self.tenstar_eqfluid)
AssertionError: {'CO2': 0.00523461217500425, 'H2O': 0.994765387824996} != {'CO2': 0.0052346121751066, 'H2O': 0.994765387824893}
- {'CO2': 0.00523461217500425, 'H2O': 0.994765387824996}
?                        ^^^^                        ^^

+ {'CO2': 0.0052346121751066, 'H2O': 0.994765387824893}
?                       + ^^                       + ^

======================================================================
FAIL: test_saturation_pressure_mysample (test_manuscript.TestManuscriptCalculations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/simonm/repos/VESIcal/tests/test_manuscript.py", line 318, in test_saturation_pressure_mysample
    self.assertDictEqual(result, self.mysample_satP)
AssertionError: {'Sat[51 chars]03374481242, 'FluidProportion_wt': 0.001816033[66 chars]4778} != {'Sat[51 chars]0337487088, 'FluidProportion_wt': 0.0018160337[65 chars]2058}
Diff is 651 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------

I'm going to switch back to figuring out the segmentation fault issue, but wanted to put this here so it is not forgotten. Since it seems to be failing on distant significant figures, it might be variable from machine to machine whether the unittests pass?

**Comment by kaylai** [comment]
Fascinating!! They are passing on my machine. Can you try rounding the values that go into the dicts and see if that fixes it?

**Comment by simonwmatthews** [comment]
On my other computer, these unittests all pass! However, a different test is failing, and the result generated on my machine is incorrect. I am 99% certain this is a bug in thermoengine, probably affecting only M1/M2 processors. I think the solution (if affected by this problem) is to run the unittests in a docker container or on the ENKI server.

**Comment by kaylai** [comment]
Oh man. I had been running tests on my work computer (Intel) and haven't on my personal computer (M2 chip) in a while... if the results are different depending on what chipset you have, that's an issue. Did you adjust the rounding of the unit tests?

**Comment by simonwmatthews** [comment]
Yes- I adjusted the tolerance of the tests in the #198 pull request. This passed on the ENKI server at least.
