### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#29]
We should discuss which license we want to use. Currently it is GPL, but this is self propagating, and I’m not sure we want that. MIT might be a better “standard” license to use. Thoughts?

**Comment by simonwmatthews** [comment]
I can't think of a situation where we wouldn't want the license to be self propagating, though I think this is more my ignorance than anything else! Did you have specific reasons in mind? I also don't mind much either way- both the GPL and MIT licenses are fine by me.

**Comment by kaylai** [comment]
Honestly, I'm not really sure either. I have recently seen more MIT licenses used for science stuff. I'll reach out to some folks who might have better insight. Otherwise we can leave it GPL for now!

**Comment by kaylai** [comment]
The more I think about this, the more I think I like the MIT license better. If no objections, I will switch to an MIT license and close this issue. We can reopen if there is any suggestions on changing this.
