### ISSUE TITLE
Complete initial checks that returned values are sensible

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#3]
Dixon can return negative volatile concentrations, others probably can, too.

**Comment by kaylai** [comment]
In the manuscript, I've done a test of comparing the results of calculate_dissolved_volatiles() for the same sample with various models. The Dixon model returns a value of ~-0.8 wt% CO2.

<IMG src="http://kaylaiacovino.com/images/MSP_plot_negvals.png">

**Comment by simonwmatthews** [comment]
Well that's fun. I'll look into this. What pressure was that calculated at?

**Comment by gordon5m** [comment]
Perhaps you’ve solved global warming?

====================
Gordon Moore, Ph.D.
Experimental Petrologist
Astromaterials Research & Exploration Science
Jacobs, NASA Johnson Space Center

2101 E NASA Pkwy
Mail Code XI3
Houston, TX, 77058

Office: (281) 483-1875
On-site email:  gordon.moore@nasa.gov

“All petrology, all of the time.”--

**Comment by kaylai** [comment]
Here is the code:
```
my_sample = {'SiO2':  77.3, 
             'TiO2':   0.08, 
             'Al2O3': 12.6, 
             'Fe2O3':  0.207,
             'Cr2O3':  0.0, 
             'FeO':    0.473, 
             'MnO':    0.0,
             'MgO':    0.03, 
             'NiO':    0.0, 
             'CoO':    0.0,
             'CaO':    0.43, 
             'Na2O':   3.98, 
             'K2O':    4.88, 
             'P2O5':   0.0, 
             'H2O':    6.5,
             'CO2':    0.05}

magsat_vols = m.calculate_dissolved_volatiles(sample=my_sample, temperature=900.0, pressure=2000.0, X_fluid=0.5, verbose=False).result

shish_vols = m.calculate_dissolved_volatiles(model='Shishkina', sample=my_sample, temperature=900.0, pressure=2000.0, X_fluid=(0.5,0.5)).result

dix_vols = m.calculate_dissolved_volatiles(model='Dixon', sample=my_sample, temperature=900.0, pressure=2000.0, X_fluid=(0.5,0.5)).result

iac_vols = m.calculate_dissolved_volatiles(model='IaconoMarziano', sample=my_sample, temperature=900.0, pressure=2000.0, X_fluid=(0.5,0.5)).result

fig, ax = plt.subplots()
plt.xlabel('H2O wt%')
plt.ylabel('CO2 wt%')
plt.xlim(0,5.0)
plt.ylim(-1.0,0.2)

ax.plot(magsat_vols["H2O"], magsat_vols["CO2"], 'o', color='blue', label="MagmaSat")
ax.plot(shish_vols[1], shish_vols[0], 'o', color='green', label="Shishkina")
ax.plot(dix_vols[1], dix_vols[0], 'o', color='red', label="Dixon")
ax.plot(iac_vols[1], iac_vols[0], 'o', color='purple', label="Iacono-Marziano")

plt.title(label="Calculate Dissolved Volatiles")
plt.legend(loc="lower left")
plt.show()
```

**Comment by gordon5m** [comment]
Which “Dixon” model are you using? Is it the PI model? If it is, you can’t use that model for rhyolites. It’s only for compositions where the CO2 dissolves purely as carbonate…
Not saying that’s why you’re getting a negative number, but maybe it is? The first thing I would check is the value of PI for this composition. If it’s negative, well then...

**Comment by kaylai** [comment]
Gordon, good point. This was a test with a rhyolite. Perhaps we should make sure the calibration check warnings are in place before investigating this too much further. That could be it! Yes, I believe this implementation of Dixon only handles dissolved CO3.

**Comment by simonwmatthews** [comment]
The bug is fixed (and I will push it shortly)! However, this raises another issue- which I am about to email you all with... (Closing here for clarity).
