### ISSUE TITLE
Figure and Table showing the calibration ranges of all models

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#33]

**Comment by PennyWieser** [comment]
What do we want for this - I think for composition, a TAS plot  - but the models vary quite a lot with how they give their calibration dataset, e.g., MagmaSat gives a TAS plot for pure H2O, pure CO2, mixed H2O-CO2. 
The dataset I got from Iacono has one tab for H2O, and another for mixed H2O-CO2, but not pure CO2. 
Perhaps just one TAS diagram with different symbols and colors - e.g., red is magmasat, squares is H2O, diamonds is H2O-CO2, dots is pure CO2. 

Also, some of this is just going to be impossible to do completely correctly, Dixon cite a paper for their H2O "Cochaway and Holloway" which is an AGU abstract, so no hope of ever getting that data (I emailed Dixon, no reply). Magmasat datasets are currently being moved so not all accessable (I'm using an internet tool instead to extract the data by clicking on each symbol in their TAS space - but cant do this in any other compositional space). 

For pressures - I guess some kind of cartoon like  the one in the magmasat paper?
![PTSpace](https://user-images.githubusercontent.com/65668673/82651704-6cfcb080-9c14-11ea-98a4-630bd0835524.PNG)

Then provide the juptyer notebook so people can make other plots if they wish (just not for magmasat - cry...)

**Comment by PennyWieser** [comment]
First go at a compositional one - bit of a problem, as some of the newer models obviously use data from the older ones - I've tried to plot them in order so you can see the older symbols on top. Any comments of ways to make this clearer appreciated. I'll do a PT one, then upload the notebook
![CalibrationRange](https://user-images.githubusercontent.com/65668673/82664640-0b474100-9c2a-11ea-9802-658913243897.png)

**Comment by kaylai** [comment]
Sorry I didn't respond to this sooner. This is looking great so far! I think the TAS diagram looks great, and it works well with the oldest models on top, as you've done.

For the PT figure... nice! One q: what is happening in the H2O plot with the gray with green dots? Is that MooreH2O overlapping IaconoH2O?

**Comment by PennyWieser** [comment]
Yes, the horrid green dots is basically the purple dotted box is underneath and then for some reason python turns the dots green.... Its hard to show that they overlap because they have the same P range... 

I was wondering with the TAS whether we also want 2 seperate diagrams, 1 for just H2O, one for H2O-CO2 +CO2 as for the PT so that it can be  a 4 - part figure? Else the TAS could sit as a part a fulll width with the 2xPT plots as parts b and c below. I guess it depends how often people will use the H2O-only models in isolation (maybe a lot in arcs?)

**Comment by kaylai** [comment]
Let's also make a table with all of this info. Changing the issue name to reflect this.

**Comment by PennyWieser** [comment]
I have put a PT and TAS figure in the figure folder. Working about best way to display in a table.

**Comment by kaylai** [comment]
@PennyWieser Do you already have a list or table of calibration range values for each model? Particularly in terms of P and T? I think a good way to show this all in a table would be like:

| Model  | P (bars) | T (C) | Composition |
| ------------- | ------------- | ----------- | ------- |
| MagmaSat  H2O | 0–20,000  | 550–1425 | Broad compositional range |
| MagmaSat CO2  | X–Y  | A–B | Broad... |
| Shishkina | blah-blah | blah-blah | SiO2>X, blah blah |

**Comment by PennyWieser** [comment]
Hi Kayla, yes, in the notebook "https://github.com/kaylai/VESIcal/blob/master/Calibration/Calibration_Datasets_Specific_Warnings.ipynb"
Scroll down to "table of calibration limits" - I will tidy it up (e.g. subscripts), but most the info is all there (still waiting on dixon to access her PC with the unpublished data used in her calibration on). I can add a short description of composition, or we could show it near the TAS diagram in the manuscript?


 I can add a broad compositional description too.

**Comment by kaylai** [comment]
This is awesome, thank you!

**Comment by PennyWieser** [comment]
closing as done as much as possible, given up on ever getting the Dixon water calibration dataset.
