### ISSUE TITLE
Tool name!

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#52]
We've been trying to decide on a name for this tool. It's really outgrown "MagmaSatPlus". Simon suggested vesical, and I've bought into VESIcal (Volatile Equilibration and Saturation Identification calculator).

Thoughts? Suggestions?

**Comment by gordon5m** [comment]
Yeah, I wondered about that name when I saw it on the manuscripts spreadsheet. ;-)
I’m cool with it!
G.

**Comment by PennyWieser** [comment]
I like VESIcal, otherwise PySol, SolPy (like numpy, pymultinest as its mostly solubility), or PyVolSol

**Comment by kaylai** [comment]
More backronym ideas:
- Volatile Equilibria and Solubility Indication calculator
- Volatile Equilibration and Solubility Inspection calculator

Another “py” idea: VolPy

For some reason I feel like VolPy should have a cute fox as a logo.

**Comment by gordon5m** [comment]
Um, duh.
So, how do we incorporate foxes into degassing?
How about Volatile Equilibria and Solubility Prediction and Assessment…I mean, if you’re going w/ an Italian theme? :)

**Comment by simonwmatthews** [comment]
I don't have a strong opinion either way, I think all the acronyms are good! I do have a thought on the 'py' names though...
Modules like numpy and scipy have 'py' in the name, which fits with their being built for python users, to make python a useful tool. However, for us python is just the tool to make the calculations work, its of little practical consequence for the majority of users that its written in python...
However... I'm sure there are just as many exceptions to this already out there! And a fox would make for an excellent logo...
As for VESIcal... I guess a logo with bubbles replacing some letters could work? Not as engaging as a fox though...

**Comment by kaylai** [comment]
Simon, good point re "py" in the name. Honestly, I'm sort of all in on a fox logo regardless of the name! I already found a cool one and made a mockup in ASCII that could be at the end of the code...here: [VESIcal_ASCII.txt](https://github.com/kaylai/MagmaSatPlus/files/4670381/VESIcal_ASCII.txt)


![volcanofox](https://user-images.githubusercontent.com/6538370/82709456-3fc8f600-9c46-11ea-8b38-22dc27de74c1.png)

**Comment by gordon5m** [comment]
Obvi, but had to be done. ;-)

https://www.youtube.com/watch?v=jofNR_WkoCE <https://www.youtube.com/watch?v=jofNR_WkoCE>

**Comment by kaylai** [comment]
I changed the name of the repository from MagmaSatPlus to VESIcal. Please let me know if this messes anything up for anyone and apologies in advance if it does... not sure how git handles that...

**Comment by simonwmatthews** [comment]
> Obvi, but had to be done. ;-) https://www.youtube.com/watch?v=jofNR_WkoCE <https://www.youtube.com/watch?v=jofNR_WkoCE>
> […](#)

Can we hide a link to the video somewhere in the code...?

**Comment by simonwmatthews** [comment]
> Simon, good point re "py" in the name. Honestly, I'm sort of all in on a fox logo regardless of the name! I already found a cool one and made a mockup in ASCII that could be at the end of the code...here: [VESIcal_ASCII.txt](https://github.com/kaylai/MagmaSatPlus/files/4670419/VESIcal_ASCII.txt)
> 
> ![MyFox](https://user-images.githubusercontent.com/6538370/82710059-9420a580-9c47-11ea-9845-244de491bd2b.png)

This is awesome!

**Comment by kaylai** [comment]
> > Obvi, but had to be done. ;-) https://www.youtube.com/watch?v=jofNR_WkoCE https://www.youtube.com/watch?v=jofNR_WkoCE
> > […](#)
> 
> Can we hide a link to the video somewhere in the code...?

YES!

**Comment by kaylai** [comment]
> > > Obvi, but had to be done. ;-) https://www.youtube.com/watch?v=jofNR_WkoCE https://www.youtube.com/watch?v=jofNR_WkoCE
> > > […](#)
> > 
> > 
> > Can we hide a link to the video somewhere in the code...?
> 
> YES!

IT IS DONE

**Comment by simonwmatthews** [comment]
I've changed the module name to VESIcal. Hopefully this won't break anything... I've not touched anything in the manuscript folder though.

**Comment by kaylai** [comment]
Just commenting to say that I got official permission from the artist to use the fox logo for VESIcal! Woohoo!
