### ISSUE TITLE
Standardise return from calculate_equilibrium_fluid_comp

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#53]
MagmaSat and MooreWater returns a dict, the other models return a tuple. Returning a dict is the better option.

**Comment by kaylai** [comment]
Sounds good! I can’t remember if I switched MooreWater to return a tuple. I will check on it when I’m back to work in the morning.

**Comment by simonwmatthews** [comment]
MooreWater was switched to returning a tuple, however, to make it consistent with the other pure fluid models, I've modified it to return a single float. It might be better to fully implement it as a MixedFluid model though. The default return for MixedFluid is now a dict.
