### ISSUE TITLE
"Melt" vs "Liquid"

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#57]
I've used the term "liquid" to refer to the melted portion of the silicate system simply because that's what MagmaSat uses... but I actually like melt better. Should I change it? Preferences?

**Comment by simonwmatthews** [comment]
I have no strong opinions... Perhaps keeping "liquid" to stay consistent with thermoengine will be best?

**Comment by gordon5m** [comment]
“Liquid” is probably best. I too like “melt” better, but that implies a process while “liquid” is the more precise phase name.

**Comment by kaylai** [comment]
Perhaps we could have a couple sentences early in the manuscript defining the terms liquid and fluid. We also use fluid and vapor interchangeably. I think "fluid" is used by MELTs?

**Comment by gordon5m** [comment]
I do believe fluid is used by MELTS (and MagmaSat)…And, yes, a section w/ definitions of terms used would be super useful for clarity.
G.

**Comment by kaylai** [comment]
Closing this issue. Have opened a new one as a "to-do" item for me to add some info on term definitions to the manuscript. Will stick with "liquid" over "melt".

#61
