### ISSUE TITLE
Units for Pressure - SI units vs. Earth Scientists

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#60]
Assigning you all to start the convo.

I notice all the models are currently outputting in bars. Should i make all the calibration figures and tables of ranges in bars also for consistency? One thing though, I have had a reviewer pull me up on using bars and was told to use SI units and talk in terms of MPa instead of kbar. I don't have a preference, just let me know if you plan to stick with bars so I can be consistent!

**Comment by simonwmatthews** [comment]
I think if that came up in review of this paper I would be tempted to reply "The wonderful thing about our new modelling framework is the user is at liberty to easily convert to their preferred units." Also true of submitting it as a Jupyter notebook...

On a more practical note, I think the best reason for retaining bars is thats the pressure unit used throughout thermoengine. Its also the unit that most people use... I would be tempted to use bars in the plots, just so it doesn't lead to any confusion about the units the model uses. What are your throughts @kaylai ?

**Comment by kaylai** [comment]
The thermoengine is actually in MPa, but I much prefer using bars and would suggest we stick with it. It may not be SI, but no one actually thinks in MPa. Either bars, kbar, or GPa. And translating is a snap, as Simon mentions.

I'd say we stick with bars and do all figures in bars, but that's my two cents.

**Comment by gordon5m** [comment]
Well, as an associate editor, I’m afraid I'm legally bound to inform you (j/k) that if we don’t get dinged by reviewers, we’ll get dinged by the editors/copy editors, particularly if it’s part of the journal’s style rules to use SI. I am personally used to converting it all in my head and don’t have a problem w/ any of them. But, if it was up to me, I’d consistently use MPa or GPa.

My 0.02,
G.

**Comment by gordon5m** [comment]
Ha ha. OK, sounds good.
G.

**Comment by simonwmatthews** [comment]
I should have been more specific- the "core" thermoengine code uses bars, I think its just the MELTS code that uses MPa. So I guess we can't be totally consistent with everything!

**Comment by kaylai** [comment]
Ahh... that's even funnier. I wonder why Mark would go with bars for the thermoengine and stick with MPa for MELTS. Maybe he also prefers bars but kept MPa in MELTs as a legacy thing... ¯\_(ツ)_/¯

**Comment by kaylai** [comment]
If we're all ok with bars for the time being, I'll call this closed. As I said, we can revisit this in review if necessary. 

Feel free to re-open if you disagree!
