### ISSUE TITLE
Bug with low volatile concentrations

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#63]
Calculations fail when volatile concentrations are low. Not sure why or where yet.

**Comment by PennyWieser** [comment]
Hi Simon, I also noticed today when running some datasets through that had H2O = 0 that most of the mixed H2O-CO2 models return a warning saying InputError: Dissolved H2O must be greater than 0 wt%, but magmasat just returns "KeyError: 'Water' " - Is it possible to get it to return a consistent error for both? 

Another thing, what are your thoughts on the user just setting H2O really, really low (e.g. 0.0001 wt%) in things like magmsat to effectively get a CO2 only model? more and more people are going to start calculating PSats this way in dryish systems, now that its clear that Raman can measure ~95% of the CO2 in some systems, its going to be hard to justify SIMS/FTIR faffing to get water. Would be good to maybe think about the best way for people to calculate Psat with magmasat if they only have C.  I actually found this bug trying to run a sensitivity test for how much H2O affects PSat as all my MI H2O has diffusively re-equilibrated (what a surprise).

**Comment by kaylai** [comment]
@PennyWieser Which calculations are throwing the KeyError for MagmaSat? I can fix that.

**Comment by PennyWieser** [comment]
![H2O_Sol_Exp](https://user-images.githubusercontent.com/65668673/83537365-5e53aa80-a4ec-11ea-9d6d-6df9280509ae.png)

**Comment by kaylai** [comment]
Just pushed a change. LMK if it is still happening for MagmaSat. Should be fixed now!

**Comment by PennyWieser** [comment]
Thanks, works now!

**Comment by simonwmatthews** [comment]
Closing this as the original issue has been fixed (I think), and Penny's comment relates to issue #28
