### ISSUE TITLE
Server times out really frequently - is there a way around this?

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#65]
This is almost certainly me being stupid, but I find the server times out on me all the time, and then restarting it takes almost 10 minutes sometimes, and quite often I just get this message and have to wait ages to try again. Is there a trick to stay connected longer? E.g. normally if I leave a long dataset going through magmasat if I check it every 10 mins if the code stops in that interval, its timed out, which means I can't download the outputs or anything
![image](https://user-images.githubusercontent.com/65668673/83541684-e0929d80-a4f1-11ea-9bd7-2434ee2a319f.png)

**Comment by kaylai** [comment]
Hmmm. So you are running this on the ENKI server? This must be an issue with the jupyter hub. I find that even running locally, sometimes I get a kernel death or timeout that kills everything. But waiting 10 minutes to restart is pretty annoying.

Perhaps we should add more explicit instructions in the documentation (I'm working on a readthedocs implementation) on how to install ENKI thermoengine and VESIcal locally. Hopefully this issue isn't happening too often? I was really hoping the ENKI server would be a robust place to host this for folks who don't do much coding.

Unfortunately, I don't think we have any control over issues with the jupyter hub, except trying to make the code as streamlined as possible. I would suggest installing ENKI thermoengine and jupyter on your local machine and then running the VESIcal stuff locally. Here are instructions for installation:
https://jupyter.org/install
https://gitlab.com/ENKI-portal/ThermoEngine

Then, you can navigate to the folder with VESIcal stuff in it in a terminal and type jupyter notebook to run jupyter. That will launch a browser window with the contents of that folder, and you can run jupyter notebooks from there.

**Comment by PennyWieser** [comment]
I am running this on the Enki server as I didn't know how to install it locally, i'll try that tomorow. - I have also had other problems that I couldn't install the TOC extension because the particular version of juptyer lab was incompatible with it (the version I had was in the "issue" of the TOC extension on github as not working). I don't know if its possible to change the version of jupyter lab the Enki thing runs automatically....

**Comment by kaylai** [comment]
> I have also had other problems that I couldn't install the TOC extension because the particular version of juptyer lab was incompatible with it (the version I had was in the "issue" of the TOC extension on github as not working).

Forgive me, what is the TOC extension?

**Comment by PennyWieser** [comment]
To get a table of contents? Maybe i'm missing something obvious, but  it makes navigating the manuscript to run specific commands challenging, as you have to scroll through the whole thing! e.g. it looks like this, 
![image](https://user-images.githubusercontent.com/65668673/83662367-4a2cad80-a5bf-11ea-86b3-894a96d0d22b.png)

while normally I have always used notebooks like this so you can click to do certain things (E.g. calculate mantle Ba contents) without scrolling through the entire script. Its not essential, but its nice!

![image](https://user-images.githubusercontent.com/65668673/83662490-76482e80-a5bf-11ea-8aeb-1d6ae247fc71.png)

**Comment by kaylai** [comment]
I've requested that the TOC extension be installed on the ENKI hub. We'll see what Mark G. says.

**Comment by simonwmatthews** [comment]
Are you running this on the production or development server?

**Comment by PennyWieser** [comment]
Development. Should i be in production?

**Comment by simonwmatthews** [comment]
I've had issues before with the development server when I've been doing computationally intensive stuff, which could be because its a mac mini sat in a home office... The production server should be more robust, and if it isn't then it is worth looking into more. You can get to the production server using server.enki-portal.org and login using gitlab (the development server is at enki.ofm-research.org).

**Comment by PennyWieser** [comment]
So it turns out I was in production (sorry, i was confused because I was working the directory notebooks - development - which I have realized is notebooks in development on the production server). Mark said to send him some errors next time it times out, so hopefully he can work on that
