### ISSUE TITLE
Return model name for batch calculations?

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#66]
I just had a thought. For batch calculations, I think it might be useful to return another column with the name of the model used (MagmaSat, Dixon, Shishkina, etc). Would this be useful?

**Comment by PennyWieser** [comment]
This would be so useful for dithery people like myself, I keep forgetting to label my outputs when i download the spreadsheet, then like 2 days later am like "man what model did I run"

**Comment by kaylai** [comment]
Implemented
