### ISSUE TITLE
MixedFluid.calculate_degassing_path method can't deal with undersaturated volatile species

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#69]
Need to make similar improvements to this method, as made for MixedFluid.calculate_saturation_pressure- i.e. correctly switching to a pure fluid throughout the whole calculation.

The symptoms of this are negative masses of fluids, and spontaneous creation of mass...

**Comment by kaylai** [comment]
The spontaneous creation of mass is an interesting problem! Nature paper?

**Comment by simonwmatthews** [comment]
Closing this for now, as I've partially solved this problem, and the remaining issues arise from bug #73
