### ISSUE TITLE
Report which samples caused an out-of-range warning for batch calculations

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#70]
Ported from Issue #40

> Also I'm wondering how people are going to use the errors we spit out for bulk calculation of PSats-It gets out of hand pretty quickly (partially because they are all erroring due to the temp offset) but even so, its doesn't' say which sample # is causing the error, so if you got 1 error out of 100 inputs, you wouldn't know which one.
> ![image](https://user-images.githubusercontent.com/65668673/84488053-8e8f0c00-ac97-11ea-965c-bd4cc19d405e.png)
> I don't know if there is any easy way to do this, but in the output spreadsheet, would it be possible to have an extra column like this so when people export, they can see what ranges were broken? Or maybe the full error message?
> ![image](https://user-images.githubusercontent.com/65668673/84488147-ab2b4400-ac97-11ea-8b62-f286737ee005.png)

Yes, that will be possible. I can add this functionality in. We should also be able to make the warning message report which sample is causing the warning.

_Originally posted by @kaylai in https://github.com/kaylai/VESIcal/issues/40#issuecomment-643376631_

**Comment by simonwmatthews** [comment]
Yep, this can be done with the CalibrationRange methods- they will just need to be called in a slightly different way. The version of the CalibrationRange routines I pushed were never meant to be the final version of this- just a work in progress. They are designed specifically for this sort of functionality. I'm happy to implement this feature? There's also no requirement to have each warning printed out, I would be tempted to use the CalibrationRange.check() methods to check each sample, record the result in columns in the spreadsheet, and then construct a single warning string afterwards.

**Comment by kaylai** [comment]
@simonwmatthews I think you implemented this by adding the "warnings" column to batch process outputs. If so, we can close this issue?
