### ISSUE TITLE
MixedFluid.calculate_equilibrium_fluid_comp() does not work correctly.

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#73]
To calculate the fluid composition for a mixed fluid the expression:
(Xt0 - Xm0)/(Xv0-Xm0) = (Xt1 - Xm1)/(Xv1-Xm1)
is solved numerically (where numbers are the volatile species, v is vapour, m is melt, and t is total). Using Xv1 = (1-Xv0), removes Xv1, and then we solve for Xv0. However, in general the solution could lie in one of three regions,
0 -> Xm0, 
Xm0 -> (1-Xm1), 
(1-Xm1) -> 1
Where the first expression goes to +ve/-ve infinity at the boundaries. This causes an issue with the root finding routine as it thinks its found the root when it finds the change from +ve to -ve. This means that the bounds must be found first, and the region identified in which the solution resides, before attempting to solve the first expression.

For any given Xv0, Xm0 and Xm1 are functions of Xv0, and so a numerical routine must be used to find each bound. Its also possible that neither bound sits within the range 0 -> 1.

I have code written that (I think) *should* do this calculation, i.e. find the bounds, identify between which bounds the solution lies, and then calculate the equilibrium fluid composition. However, I can't get it to work. Debugging led me to the point where I would call a function manually with (what I think) are identical values, and get a completely different answer to the one the root-finders are seeing. I have no idea why. The confusion is also compounded by a git-related mess-up on my part where I lost some of the code used in the debugging...

At the moment this new code is in the module, but commented out. The existing code runs most of the time, but will probably produce incorrect results. This also means the degassing path calculations produce incorrect results (sometimes producing mass from nowhere!).

I've hit a dead-end with debugging this for now, and so have documented the issues here. I may be missing something obvious though... I also have an idea for an entirely different way of calculating it, but will take me some time to implement...

**Comment by simonwmatthews** [comment]
Fixed, I think. Needs some thorough testing, but its certainly working for the tests I've run.

**Comment by kaylai** [comment]
I'm having some issues with this. I tested it on all the MixedFluid models using this sample:

```python
wtpt_oxides = pd.Series({'SiO2':47.95,
                         'TiO2':1.67,
                         'Al2O3':17.32,
                         'FeO':10.24,
                         'MgO':5.76,
                         'CaO':10.93,
                         'Na2O':3.45,
                         'K2O':1.99,
                         'P2O5':0.51,
                         'CO2':0.8,
                         'H2O':4.0})
```

My function call:
```python
v.calculate_saturation_pressure(sample=wtpt_oxides, temperature=1000, model='Shishkina').result
```

The output:
`nan`

I've been making edits to things, but I *think* I merged your recent changes correctly, so I don't think it's my new code. What sample did you test on?
