### ISSUE TITLE
Advising users what to do when data has FeOT column heading

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#83]
This is probably super obvious to anyone who can go into and look at the code, but if you load in a spreadsheet with a column for FeOT as a header instead of FeO (as a lot of literature data is presented), it does the calculations assuming no FeO or Fe2O3. I made this mistake by accident today, and only realized because it didnt match the literature PSat.

 It might be worth clarifying somewhere very clearly that that code will not recognise FeOT = FeO (as other programs like petrolog will). Is there any easy way to return an error if someone has the heading FeOT - like "the code will not assume this is FeO, but will just deal with it as an unrecognised column).  Else you get meaningless results without getting an error, so you wouldn't necessarily know you've provided a silly input.

**Comment by kaylai** [comment]
Ahhh yes, see, these are the kinds of things I easily forget about, so I am grateful to you for catching it!

What I would like to do is to code up an fO2 routine using, say, Kress and Carmichael, which would allow users to select an fO2 and then the FeO/Fe2O3 is calculated for them.

For now, I have simply warned the user about it. If FeOt is passed and no FeO column is passed, FeOt values are used as FeO. If FeOt and FeO columns are passed, FeOt is ignored.

Commit 1480e2b5cccc14eedeb4148ca0a497cd5f7321e0

**Comment by PennyWieser** [comment]
Sorry to be such a pain about this, in the Moore dataset, most of the samples have FeO, and Fe2O3 separated out. But some have just FeO, which is FeOT. Thus, there are three columns. Vesical at the moment returns this
![image](https://user-images.githubusercontent.com/65668673/88455378-b82d7c80-ce6c-11ea-830b-9207f55771d1.png)
However, is there an easy way to get it to check, like if FeO and Fe2O3 are 0, or empty, at that point it decides to use FeOT? Else at the moment, its setting FeO to 0 for the samples where it was expressed as FeOT

**Comment by kaylai** [comment]
Not a pain at all! I think I can change the code to check each row rather than the entire spreadsheet. Will have a go at that and report back.

**Comment by kaylai** [comment]
Should be fixed now! Let me know if you run into other issues.

Commit 7fb183b2489e1120841ae4411e8d3101db7030f5
