### ISSUE TITLE
Return of NaN for test samples on calculate_equilibrium_fluid with MixedFluid() models

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#86]
I'm having some issues with this. It seems to work fine on single-fluid calls (e.g. 'ShishkinaWater'). I tested it on all the MixedFluid models using this sample as well as some rhyolites:

```python
wtpt_oxides = pd.Series({'SiO2':47.95,
                         'TiO2':1.67,
                         'Al2O3':17.32,
                         'FeO':10.24,
                         'MgO':5.76,
                         'CaO':10.93,
                         'Na2O':3.45,
                         'K2O':1.99,
                         'P2O5':0.51,
                         'CO2':0.8,
                         'H2O':4.0})
```

My function call:
```python
v.calculate_saturation_pressure(sample=wtpt_oxides, temperature=1000, model='AnyMixedFluidModel').result
```

The output:
`nan`

I've been making edits to things, but I *think* I merged Simon's recent changes correctly, so I don't think it's my new code. Suggestions?

**Comment by simonwmatthews** [comment]
I just tried running exactly the same code, and it works fine for me, so I'm not sure why its not working... I'm using the latest version on github.

**Comment by kaylai** [comment]
You're right. It was a problem as I was importing Sympy as "from sympy import *", which I know is a no-no. Changed to "import sympy" and added "sympy." before the sympy functions I'm using, and it's fixed!
