### ISSUE TITLE
Bug in MixedFluid().calculate_degassing_path

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#87]
I was doing some testing on calculate_degassing_path for MixedFluid models, and I noticed something odd. I think the H2O_fl and CO2_fl are being reported (and potentially used?) backwards. This may not actually affect the results.

Input:
```python
#Experimental sample from Tamic et al. (2001)
Ech6 = pd.Series({'SiO2':77.04,
                         'TiO2':0.11,
                         'Al2O3':12.76,
                         'FeO':0.68,
                         'MnO': 0.07,
                         'MgO':0.08,
                         'CaO':0.58,
                         'Na2O':4.07,
                         'K2O':4.79,
                         'CO2':0.066,
                         'H2O':3.84})

path=v.calculate_degassing_path(sample=Ech6, temperature=800, model='Dixon').result
path
```

Output:
```python
     Pressure_bars   H2O_liq   CO2_liq    H2O_fl    CO2_fl  FluidProportion_wt
0      4351.055097  3.840000  0.066000  0.951711  0.048289            0.000000
1      4308.544546  3.818605  0.063411  0.952786  0.047214            0.023985
2      4266.033995  3.797195  0.060937  0.953810  0.046190            0.047868
3      4223.523444  3.775779  0.058573  0.954786  0.045214            0.071648
4      4181.012893  3.754364  0.056310  0.955720  0.044280            0.095326
..             ...       ...       ...       ...       ...                 ...
96      270.042204  1.502831  0.000144  0.988594  0.011406            2.403025
97      227.531653  1.404952  0.000115  0.989043  0.010957            2.500933
98      185.021102  1.291321  0.000089  0.989522  0.010478            2.614591
99      142.510551  1.156768  0.000065  0.990039  0.009961            2.749167
100     100.000000  0.991761  0.000043  0.990607  0.009393            2.914197
```

Now, let's test that first row...

Input:
```python
v.calculate_dissolved_volatiles(sample=Ech6, pressure=4351, temperature=800, X_fluid=0.951711, model='Dixon').result
```

Output:
```python
{'CO2': 0.4267017257128844, 'H2O': 1.0855602150957062}
```

Now, if I switch X_fluid to the value given for CO2_fl...

Input:
```python
v.calculate_dissolved_volatiles(sample=Ech6, pressure=4351, temperature=800, X_fluid=0.048289, model='Dixon').result
```

I get the correct answer:

Output:
```python
{'CO2': 0.06599846602043563, 'H2O': 3.8399687970691896}
```

I would take a crack at fixing this, but I worry that it's actually being used in some way that my fix would complicate that.

**Comment by simonwmatthews** [comment]
When X_fluid is a single float, it assigns that to the first volatile species in self.volatile_species, which for all the default models is CO2. If you want it to be H2O instead, the default model definitions should be changed so that the H2O model is defined first, i.e.,
Instead of:
`MixedFluid({'CO2':ShishkinaCarbon(),'H2O':ShishkinaWater()})`
use
`MixedFluid({'H2O':ShishkinaWater(),'CO2':ShishkinaCarbon()})`

Making this change shouldn't break any of the MixedFluid calculations, but might break the batch calculations, depending on whether they check the order of the volatile species.

**Comment by simonwmatthews** [comment]
Ok, just checked the batch calculations, they shouldn't be affected if the switch is made.

**Comment by simonwmatthews** [comment]
I just tried switching them. For some reason the root solver in calculate_equilibrium_fluid_comp() fails when they're switched. Not sure why this is, definitely worth figuring out at some point, but I'm going to leave it for now.

**Comment by simonwmatthews** [comment]
Found the issue with the root solver and have switched CO2 and H2O in the default models, so everything should be consistent now :).
