### ISSUE TITLE
final_pressure argument in calculate_degassing_path does not get set

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#88]
Bug: setting a value for the argument final_pressure when calling calculate_degassing_path does nothing.

Example input:
```python
path=v.calculate_degassing_path(sample=Ech6, temperature=800, model='Liu', final_pressure=1.0).result
```

Still only calculates for pressures down to 100.0 bars.

**Comment by simonwmatthews** [comment]
Forgot to update the call to the MixedFluid function, within the class. Now fixed.
