### ISSUE TITLE
Incorporate H2O speciation into molecular mass calculation in DixonWater model

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#93]
I think the small discrepancy that exists in the Dixon model with other implementations might be coming from not taking into account H2O speciation when calculating the molecular mass.

**Comment by PennyWieser** [comment]
Hi @simonwmatthews  https://github.com/DJRgeoscience/VolatileCalcForPython Dan R has uploaded his script for volatilecalc for python that might help resolve these issues!

**Comment by simonwmatthews** [comment]
Closing this issue as this doesn't seem to be the problem. The remaining issue is covered in issue #101
