### ISSUE TITLE
Shishkina Mixed Fluid shows strange behaviour vs. other hybrids

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#94]
I have been playing around with the sensitivies of the different models to the melt H2O content by running a constant composition, same C content (50 ppm in the case i've uploaded to Testing", varying H2O up to ~1.5 wt%). . Shishkina (using Shishkina Carbon and Shishkina water) does not output a different pressure for changing water contents between 0 and 1. When I hybridize shishkina carbon with Moore or Liu or Iacono-Marziano water though, it shows similar sensitivity to all the other models. 
![image](https://user-images.githubusercontent.com/65668673/86104970-a4ce0200-bab6-11ea-9455-7d25631e6992.png)

Files:
WaterSensitivity_50ppm.ipynb
WaterSensitivity_50ppm.xlsx

**Comment by simonwmatthews** [comment]
This is a 'feature' of the model- at 0 bar there is a finite water solubility. I was slightly puzzled by this too, but that's the behaviour the equations predict. Of course, there might be a mistake in the equations... Is it easy to repeat the analysis with the webapp?

**Comment by PennyWieser** [comment]
@kaylai The stepped behaviour of magmasat is odd  - is there some rounding going on in the code? e.g., does it only return answers to the nearest MPa?  the output suggest this is the case? Or is this just a fundamental sensitivity limitation of the model. 
![image](https://user-images.githubusercontent.com/65668673/86109359-355b1100-babc-11ea-9fde-e4f0d463f798.png). Its not the end of the world, I'm just curious (obviously 1MPa is going to be overwhelmed by other errors anyway)

**Comment by PennyWieser** [comment]
@simonwmatthews yup its the very high solubility at low pressure, ~ 1wt% -  their graphs do actually show this. 
![image](https://user-images.githubusercontent.com/65668673/86110842-f5952900-babd-11ea-906f-30a005298616.png) 
I guess i'll just add this in the description,- Its interesting, given most use of Shishkina will be in dry basalts (e.g., Hawaii, Iceland, Galapagos) where you could actually get away with just using ShishkinaCarbon. @kaylai Simon and I discussed whether it would be worth having an adapted figure of the above to show this? 

Interestingly, for the same composition at 500 ppm, you get weird jumps in the Dixon and Iacono-Marziano (likely to do with the other issues Simon was talking about). 
![image](https://user-images.githubusercontent.com/65668673/86116360-32185300-bac5-11ea-8d4e-64d7e5e599be.png)
I've also uploaded this script. 

Finally, for isobars for Shishkina, it doesn't plot anything below 1 wt% H2O (but the others models do) - is this because the code gets stuck or something once water is at 1 wt% value? It would be good if it did extend it over, so people could see the strange behavoir of this model at 0-1 wt% water
![image](https://user-images.githubusercontent.com/65668673/86118930-7dccfb80-bac9-11ea-9ad2-72c86b49f173.png)

**Comment by kaylai** [comment]
> @kaylai The stepped behaviour of magmasat is odd - is there some rounding going on in the code? e.g., does it only return answers to the nearest MPa? the output suggest this is the case? Or is this just a fundamental sensitivity limitation of the model.
> ![image](https://user-images.githubusercontent.com/65668673/86109359-355b1100-babc-11ea-9fde-e4f0d463f798.png). Its not the end of the world, I'm just curious (obviously 1MPa is going to be overwhelmed by other errors anyway)

@PennyWieser I think I know what's causing this. I've opened an new issue (#95) and will try and fix asap. Thanks for flagging this.

**Comment by simonwmatthews** [comment]
For the Shishkina isobars- the routine only calculates between Xfluid=0 and Xfluid=1, so doesn't return any values less than 1 wt%. I think the best way to handle this is in the plotting script. I can make this change, but thought I would check that everyone is in agreement first?

**Comment by simonwmatthews** [comment]
I'm not sure why there are jumps in the saturation pressure returned by some of the other models. I'll have a look at the script and try to find the bug.

**Comment by PennyWieser** [comment]
Good news - the jumps seem to have disapeared due to the fixes from the web app. Success!
![image](https://user-images.githubusercontent.com/65668673/87070088-34d71e80-c210-11ea-984b-fed0dfbc9cfb.png)

**Comment by kaylai** [comment]
@simonwmatthews Reopening this. For some reason the extend_isobars_to_zero=True doesn't seem to be working for me for Shishikina. Is it supposed to? I assumed all the models now extended to zero. Apologies if I am forgetting something...
<img width="1097" alt="Screen Shot 2020-08-19 at 5 35 30 PM" src="https://user-images.githubusercontent.com/6538370/90696883-c6d83b00-e242-11ea-8499-98af343717d8.png">

Code to reproduce:
```python
alkbasalt = {'SiO2': 49.0, 
                'TiO2': 1.27, 
                'Al2O3': 19.7, 
                'Fe2O3': 3.74, 
                'FeO': 5.33,
                'MnO': 0.17, 
                'MgO': 4.82, 
                'CaO': 8.85, 
                'Na2O': 4.23, 
                'K2O': 1.00, 
                'P2O5': 0.37,
                'H2O': 4.51,
                'CO2': 0.25}

Shish_alkbasalt_isobars, Shish_alkbasalt_isopleths = v.calculate_isobars_and_isopleths(sample=alkbasalt, temperature=1200, pressure_list=[500, 1000, 2000], isopleth_list=[0, 0.5], model="Shishkina").result

v.plot(isobars=Shish_alkbasalt_isobars)
```

**Comment by simonwmatthews** [comment]
The extend-to-zero code was only implemented in the smoothed part of the code. I've reproduced it for the non-soothed part now, and it appears to be working correctly.
