### ISSUE TITLE
Bug in MagmaSat batch Saturation pressure calculations

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#95]
@kaylai The stepped behaviour of magmasat is odd  - is there some rounding going on in the code? e.g., does it only return answers to the nearest MPa?  the output suggest this is the case? Or is this just a fundamental sensitivity limitation of the model. 
![image](https://user-images.githubusercontent.com/65668673/86109359-355b1100-babc-11ea-9fde-e4f0d463f798.png). Its not the end of the world, I'm just curious (obviously 1MPa is going to be overwhelmed by other errors anyway)

_Originally posted by @PennyWieser in https://github.com/kaylai/VESIcal/issues/94#issuecomment-651676707_

**Comment by kaylai** [comment]
@PennyWieser Can you tell me the code you wrote to do this calculation? I am working on it and think it only happens in certain conditions so want to be sure that's the behavior you are seeing, too.

**Comment by PennyWieser** [comment]
Hi Kayla, sorry for the delay - I should have said, the codes are here:
https://github.com/kaylai/VESIcal/blob/master/Calibration/Testing/WaterSensitivity_500ppm.ipynb
https://github.com/kaylai/VESIcal/blob/master/Calibration/Testing/WaterSensitivity_50ppm.ipynb

**Comment by kaylai** [comment]
I discovered that making the search for saturation pressure any finer than 10 bars (1 MPa) causes errors in some samples on in the thermoengine C code. This isn't something I can fix or even handle in python. Unfortunately, the precision of the MagmaSat calculate_saturation_pressure routine will have to remain at 10 bars. But, realistically, it's not that accurate anyways (given errors inherent to what we know about the system, the experiments that have gone into the calibration, etc). So I think this will have to just be OK.

Closing this issue, as I don't plan to fix this unless something magical happens.

**Comment by PennyWieser** [comment]
Hi @kaylai thats fine - I'll just add in the figure caption for this figure that this is the cause of the stepped behaviour. I'm assuming we do want a figure showing the different responses for a given composition for variable H2O? Will be useful for basaltic people working in dry systems I think - If not, no worries, i'll put the figure in my Kilauea paper instead.

**Comment by kaylai** [comment]
Yes, that is a potentially quite useful figure!
