### ISSUE TITLE
Alterating v.plot_isobars_and_isopleths/smoothed outputs for v.calculate

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#97]
Hi Kayla, 
I was wondering if there was any easy way to get VESIcal to output the smoothed outputs you've done for 
"v.plot_isobars_and_isopleths(isobars, isopleths)" when people call v.calculate_isobars_and_isopleths?
Currently, while i'm testing the isobars/isopleths against published data, I am finding it hard to adjust the "v.plot_isobars_and_isopleths(isobars, isopleths)" to say only show isobars, or adjust the axes limits so I can overlay it on literature figures. How would you, say, adjust this to set a y limit? 

But I think, generally, it would be better if people get 4 outputs from v.calculate, the raw ones, and also the smoothed ones so they can take these outputs and plot them on whatever graphs they wish? E.g., output isobars, isopleths, and isobars_smoothed, isopleths_smoothed? Then they can also plot them both together to check the smoothing is actually doing a good job, if, say they haven't entered enough points?

**Comment by kaylai** [comment]
Done! I've created a new method called 

`smooth_isobars_and_isopleths()`

Here is the docstring explaining how the method works:
```python
def plot_isobars_and_isopleths(isobars, isopleths):
	"""
	Takes in a dataframe with calculated isobar and isopleth information (e.g., output from calculate_isobars_and_isopleths)
	and plots data as isobars (lines of constant pressure) and isopleths (lines of constant fluid composition). These lines
	represent the saturation pressures of the melt composition used to calculate the isobar and isopleth information.

	Parameters
	----------
	isobars: pandas DataFrame
		DataFrame object containing isobar information as calculated by calculate_isobars_and_isopleths.

	isopleths: pandas DataFrame
		DataFrame object containing isopleth information as calculated by calculate_isobars_and_isopleths.

	Returns
	-------
	matplotlib object
		Plot with x-axis as H2O wt% in the melt and y-axis as CO2 wt% in the melt. Isobars, or lines of
		constant pressure at which the sample magma composition is saturated, and isopleths, or lines of constant
		fluid composition at which the sample magma composition is saturated, are plotted.
	"""
```

You can calculate both isobars and isopleths or either one of those by itself. For example, to calculate isobars only, you can do:

```python
import VESIcal as v
isobars, isopleths = v.calcualte_isobars_and_isopleths(sample=your_sample, temperature=your_temp, pressure_list=[1000,2000]).result
smoothed_isobars = v.smooth_isobars_and_isopleths(isobars)
```

smoothed_isobars is now a pandas dataframe with column names corresponding to the pressure values. For example, in the example above, your columns would be named '1000xvals', '1000yvals', '2000xvals', and '2000yvals'. They are accessed like:

```python
print(smoothed_isobars['1000xvals'])
```

or plotted like:
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot(smoothed_isobars['1000xvals'], smoothed_isobars['1000yvals'])
ax.plot(smoothed_isobars['2000xvals'], smoothed_isobars['2000yvals'])
plt.show()
```
