### ISSUE TITLE
Allison Carbon returns a lot of Nans - Means mixed fluids 

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#99]
Hi @simonwmatthews 
I know we discussed this briefly on skype the other day, but the Allison model is doing some pretty funky things. 
Specifically, AllisonCarbon returns a lot of Nans. E.g., 
# Doesn't ever seem to return a Nan for CO2<0.04 wt% 
# Return Nan if H2O<1 wt%, CO2=0.05 wt%
# Return Nan if H2O<5 wt%, CO2=0.06 wt%
# Return Nan if H2O<11 wt%, CO2=0.07 wt%
# Return Nan if H2O<17 wt%, CO2=0.08 wt%
# Return Nan if H2O<36 wt%, CO2=0.1 wt%
When I run as a single composition using:
test=v.calculate_saturation_pressure(sample=my_sample, temperature=1200, verbose=True, model='AllisonCarbon', fit='thermodynamic', loc='sunset').result
It just spits out "nan" rather than giving an error so I don't know what the problem is. 

When run as a batch, it spits out this error:
/home/jovyan/ThermoEngine/Notebooks/Development/Final_Model_Tests_Agree/VESIcal.py:5071: RuntimeWarning: Saturation pressure not found.
  warnings.warn("Saturation pressure not found.",RuntimeWarning)

Crucially, the big problem is, it seems even if AllisonCarbon turns a Nan, the mixed fluid models build from AllisonCarbon+ water still return an output - my gut feel is that if either C or H model in a mixed fluid model returns a Nan for any given composition, the mixed fluid model should also return a Nan, else you could be very mislead by the results - in these cases, get very low saturation pressures, as only looking at the H2O. 

Scripts are Testing_Allison_et_al_2019.pynb and xlsx.

**Comment by PennyWieser** [comment]
Hi @simonwmatthews 
Allison Carbon now actually returns outputs (whoop) and pressures increase with increasing CO2. - just to check, has the fix been implemented where if one of H2O or CO2 model returns a nan the mixed model does too?

However, AllisonCarbon still shows a drop in PSat with increasing H2O. 
![image](https://user-images.githubusercontent.com/65668673/87132658-1c0d4e00-c28e-11ea-9a7f-76f29f414326.png)

This is also seen in the mixed models (I'm assuming being lead by the fact the C model is doing this?)
![image](https://user-images.githubusercontent.com/65668673/87132792-4b23bf80-c28e-11ea-8a42-d327c1ecbfac.png)

**Comment by simonwmatthews** [comment]
The variation with H2O content was coming from the formula weight being calculated with H2O included, so as H2O content increased, the mass proportion of CO2 in the magma also increased. I don't *think* this is the behaviour we want, but further testing should reveal this. I've removed H2O from the formula weight calculation for now.

I've not changed the NaN return behaviour for MixedFluid yet, but will do this now.

**Comment by simonwmatthews** [comment]
Looks like there's still some offsets at H2O = 0 wt%. Will look into this now.

**Comment by simonwmatthews** [comment]
The offsets should be fixed now, so I'm going to close this issue. Returning NaNs from MixedFluid is not as straightforward as I had hoped, so I will give some more thought to this before doing anything.
